apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drizzgw-gateway-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drizzgw-gateway-pods
subjects:
  - kind: ServiceAccount
    name: drizzgw
