apiVersion: apps/v1
kind: Deployment
metadata:
  name: drizzgw-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drizzgw
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drizzgw
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: drizzgw
      containers:
        - name: drizzgw
          image: caredai/drizzgw:latest
          args: ['--server']
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drizzgw-config
            - secretRef:
                name: drizzgw-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
