packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.90.7
  ai: 5.0.38
  eslint: ^9.39.1
  prettier: ^3.6.2
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  typescript: ^5.9.3
  # The version of `zod` should be the same across all packages and dependencies.
  # Otherwise, you may get the following error:
  #   Type instantiation is excessively deep and possibly infinite
  zod: 4.1.12
  hono: ^4.11.1

catalogs:
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: ^19.2.0
    react-dom: ^19.2.0
