packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!packages/workflow'

catalog:
  "@tanstack/react-query": ^5.66.7
  "@trpc/client": ^11.1.0
  "@trpc/server": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  eslint: ^9.18.0
  prettier: ^3.4.2
  tailwindcss: ^4.0.10
  typescript: ^5.7.3
  # The version of `zod` should be the same across all packages and dependencies.
  # Otherwise, you may get the following error:
  #   Type instantiation is excessively deep and possibly infinite
  zod: ^3.25.51
  ai: 5.0.38

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
