// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type Command = {
    command: string;
    exitCode?: number;
    id: string;
};

export type CompletionContext = {
    triggerCharacter?: string;
    triggerKind: number;
};

export type CompletionItem = {
    detail?: string;
    documentation?: unknown;
    filterText?: string;
    insertText?: string;
    kind?: number;
    label: string;
    sortText?: string;
};

export type CompletionList = {
    isIncomplete: boolean;
    items: Array<CompletionItem>;
};

export type ComputerUseStartResponse = {
    message?: string;
    status?: {
        [key: string]: ProcessStatus;
    };
};

export type ComputerUseStatusResponse = {
    status?: string;
};

export type ComputerUseStopResponse = {
    message?: string;
    status?: {
        [key: string]: ProcessStatus;
    };
};

export type CreateContextRequest = {
    cwd?: string;
    language?: string;
};

export type CreateSessionRequest = {
    sessionId: string;
};

export type DisplayInfo = {
    height?: number;
    id?: number;
    isActive?: boolean;
    width?: number;
    x?: number;
    y?: number;
};

export type DisplayInfoResponse = {
    displays?: Array<DisplayInfo>;
};

export type Empty = {
    [key: string]: unknown;
};

export type ExecuteRequest = {
    command: string;
    /**
     * Current working directory
     */
    cwd?: string;
    /**
     * Timeout in seconds, defaults to 10 seconds
     */
    timeout?: number;
};

export type ExecuteResponse = {
    exitCode?: number;
    result: string;
};

export type FileInfo = {
    group: string;
    isDir: boolean;
    modTime: string;
    mode: string;
    name: string;
    owner: string;
    permissions: string;
    size: number;
};

export type FileStatus = {
    extra: string;
    name: string;
    staging: Status;
    worktree: Status;
};

export type FilesDownloadRequest = {
    paths: Array<string>;
};

export type GitAddRequest = {
    /**
     * files to add (use . for all files)
     */
    files: Array<string>;
    path: string;
};

export type GitBranchRequest = {
    name: string;
    path: string;
};

export type GitCheckoutRequest = {
    branch: string;
    path: string;
};

export type GitCloneRequest = {
    branch?: string;
    commit_id?: string;
    password?: string;
    path: string;
    url: string;
    username?: string;
};

export type GitCommitInfo = {
    author: string;
    email: string;
    hash: string;
    message: string;
    timestamp: string;
};

export type GitCommitRequest = {
    allow_empty?: boolean;
    author: string;
    email: string;
    message: string;
    path: string;
};

export type GitCommitResponse = {
    hash: string;
};

export type GitRepoRequest = {
    password?: string;
    path: string;
    username?: string;
};

export type GitStatus = {
    ahead?: number;
    behind?: number;
    branchPublished?: boolean;
    currentBranch: string;
    fileStatus: Array<FileStatus>;
};

export type InterpreterContext = {
    active: boolean;
    createdAt: string;
    cwd: string;
    id: string;
    language: string;
};

export type IsPortInUseResponse = {
    isInUse?: boolean;
};

export type KeyboardHotkeyRequest = {
    /**
     * e.g., "ctrl+c", "cmd+v"
     */
    keys?: string;
};

export type KeyboardPressRequest = {
    key?: string;
    /**
     * ctrl, alt, shift, cmd
     */
    modifiers?: Array<string>;
};

export type KeyboardTypeRequest = {
    /**
     * milliseconds between keystrokes
     */
    delay?: number;
    text?: string;
};

export type ListBranchResponse = {
    branches: Array<string>;
};

export type ListContextsResponse = {
    contexts: Array<InterpreterContext>;
};

export type ListRecordingsResponse = {
    recordings: Array<Recording>;
};

export type LspCompletionParams = {
    context?: CompletionContext;
    languageId: string;
    pathToProject: string;
    position: LspPosition;
    uri: string;
};

export type LspDocumentRequest = {
    languageId: string;
    pathToProject: string;
    uri: string;
};

export type LspLocation = {
    range: LspRange;
    uri: string;
};

export type LspPosition = {
    character: number;
    line: number;
};

export type LspRange = {
    end: LspPosition;
    start: LspPosition;
};

export type LspServerRequest = {
    languageId: string;
    pathToProject: string;
};

export type LspSymbol = {
    kind: number;
    location: LspLocation;
    name: string;
};

export type Match = {
    content: string;
    file: string;
    line: number;
};

export type MouseClickRequest = {
    /**
     * left, right, middle
     */
    button?: string;
    double?: boolean;
    x?: number;
    y?: number;
};

export type MouseClickResponse = {
    x?: number;
    y?: number;
};

export type MouseDragRequest = {
    button?: string;
    endX?: number;
    endY?: number;
    startX?: number;
    startY?: number;
};

export type MouseDragResponse = {
    x?: number;
    y?: number;
};

export type MouseMoveRequest = {
    x?: number;
    y?: number;
};

export type MousePositionResponse = {
    x?: number;
    y?: number;
};

export type MouseScrollRequest = {
    amount?: number;
    /**
     * up, down
     */
    direction?: string;
    x?: number;
    y?: number;
};

export type PortList = {
    ports?: Array<number>;
};

export type Position = {
    x?: number;
    y?: number;
};

export type ProcessErrorsResponse = {
    errors?: string;
    processName?: string;
};

export type ProcessLogsResponse = {
    logs?: string;
    processName?: string;
};

export type ProcessRestartResponse = {
    message?: string;
    processName?: string;
};

export type ProcessStatus = {
    autoRestart?: boolean;
    pid?: number;
    priority?: number;
    running?: boolean;
};

export type ProcessStatusResponse = {
    processName?: string;
    running?: boolean;
};

export type PtyCreateRequest = {
    cols?: number;
    cwd?: string;
    envs?: {
        [key: string]: string;
    };
    id?: string;
    /**
     * Don't start PTY until first client connects
     */
    lazyStart?: boolean;
    rows?: number;
};

export type PtyCreateResponse = {
    sessionId: string;
};

export type PtyListResponse = {
    sessions: Array<PtySessionInfo>;
};

export type PtyResizeRequest = {
    cols: number;
    rows: number;
};

export type PtySessionInfo = {
    active: boolean;
    cols: number;
    createdAt: string;
    cwd: string;
    envs: {
        [key: string]: string;
    };
    id: string;
    /**
     * Whether this session uses lazy start
     */
    lazyStart: boolean;
    rows: number;
};

export type Recording = {
    durationSeconds?: number;
    endTime?: string;
    fileName: string;
    filePath: string;
    id: string;
    sizeBytes?: number;
    startTime: string;
    status: string;
};

export type ReplaceRequest = {
    files: Array<string>;
    newValue: string;
    pattern: string;
};

export type ReplaceResult = {
    error?: string;
    file?: string;
    success?: boolean;
};

export type ScreenshotResponse = {
    cursorPosition?: Position;
    screenshot?: string;
    sizeBytes?: number;
};

export type ScrollResponse = {
    success?: boolean;
};

export type SearchFilesResponse = {
    files: Array<string>;
};

export type Session = {
    commands: Array<Command>;
    sessionId: string;
};

export type SessionExecuteRequest = {
    async?: boolean;
    command: string;
    runAsync?: boolean;
};

export type SessionExecuteResponse = {
    cmdId: string;
    exitCode?: number;
    output?: string;
    stderr?: string;
    stdout?: string;
};

export type SessionSendInputRequest = {
    data: string;
};

export type StartRecordingRequest = {
    label?: string;
};

export type Status = 'Unmodified' | 'Untracked' | 'Modified' | 'Added' | 'Deleted' | 'Renamed' | 'Copied' | 'Updated but unmerged';

export type StopRecordingRequest = {
    id: string;
};

export type UserHomeDirResponse = {
    dir: string;
};

export type WindowInfo = {
    height?: number;
    id?: number;
    isActive?: boolean;
    title?: string;
    width?: number;
    x?: number;
    y?: number;
};

export type WindowsResponse = {
    windows?: Array<WindowInfo>;
};

export type WorkDirResponse = {
    dir: string;
};

export type GinH = {
    [key: string]: unknown;
};

export type GitGitDeleteBranchRequest = {
    name: string;
    path: string;
};

export type GetDisplayInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/display/info';
};

export type GetDisplayInfoResponses = {
    /**
     * OK
     */
    200: DisplayInfoResponse;
};

export type GetDisplayInfoResponse = GetDisplayInfoResponses[keyof GetDisplayInfoResponses];

export type GetWindowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/display/windows';
};

export type GetWindowsResponses = {
    /**
     * OK
     */
    200: WindowsResponse;
};

export type GetWindowsResponse = GetWindowsResponses[keyof GetWindowsResponses];

export type PressHotkeyData = {
    /**
     * Hotkey press request
     */
    body: KeyboardHotkeyRequest;
    path?: never;
    query?: never;
    url: '/computeruse/keyboard/hotkey';
};

export type PressHotkeyResponses = {
    /**
     * OK
     */
    200: Empty;
};

export type PressHotkeyResponse = PressHotkeyResponses[keyof PressHotkeyResponses];

export type PressKeyData = {
    /**
     * Key press request
     */
    body: KeyboardPressRequest;
    path?: never;
    query?: never;
    url: '/computeruse/keyboard/key';
};

export type PressKeyResponses = {
    /**
     * OK
     */
    200: Empty;
};

export type PressKeyResponse = PressKeyResponses[keyof PressKeyResponses];

export type TypeTextData = {
    /**
     * Text typing request
     */
    body: KeyboardTypeRequest;
    path?: never;
    query?: never;
    url: '/computeruse/keyboard/type';
};

export type TypeTextResponses = {
    /**
     * OK
     */
    200: Empty;
};

export type TypeTextResponse = TypeTextResponses[keyof TypeTextResponses];

export type ClickData = {
    /**
     * Mouse click request
     */
    body: MouseClickRequest;
    path?: never;
    query?: never;
    url: '/computeruse/mouse/click';
};

export type ClickResponses = {
    /**
     * OK
     */
    200: MouseClickResponse;
};

export type ClickResponse = ClickResponses[keyof ClickResponses];

export type DragData = {
    /**
     * Mouse drag request
     */
    body: MouseDragRequest;
    path?: never;
    query?: never;
    url: '/computeruse/mouse/drag';
};

export type DragResponses = {
    /**
     * OK
     */
    200: MouseDragResponse;
};

export type DragResponse = DragResponses[keyof DragResponses];

export type MoveMouseData = {
    /**
     * Mouse move request
     */
    body: MouseMoveRequest;
    path?: never;
    query?: never;
    url: '/computeruse/mouse/move';
};

export type MoveMouseResponses = {
    /**
     * OK
     */
    200: MousePositionResponse;
};

export type MoveMouseResponse = MoveMouseResponses[keyof MoveMouseResponses];

export type GetMousePositionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/mouse/position';
};

export type GetMousePositionResponses = {
    /**
     * OK
     */
    200: MousePositionResponse;
};

export type GetMousePositionResponse = GetMousePositionResponses[keyof GetMousePositionResponses];

export type ScrollData = {
    /**
     * Mouse scroll request
     */
    body: MouseScrollRequest;
    path?: never;
    query?: never;
    url: '/computeruse/mouse/scroll';
};

export type ScrollResponses = {
    /**
     * OK
     */
    200: ScrollResponse;
};

export type ScrollResponse2 = ScrollResponses[keyof ScrollResponses];

export type GetComputerUseStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/process-status';
};

export type GetComputerUseStatusResponses = {
    /**
     * OK
     */
    200: ComputerUseStatusResponse;
};

export type GetComputerUseStatusResponse = GetComputerUseStatusResponses[keyof GetComputerUseStatusResponses];

export type GetProcessErrorsData = {
    body?: never;
    path: {
        /**
         * Process name to get errors for
         */
        processName: string;
    };
    query?: never;
    url: '/computeruse/process/{processName}/errors';
};

export type GetProcessErrorsResponses = {
    /**
     * OK
     */
    200: ProcessErrorsResponse;
};

export type GetProcessErrorsResponse = GetProcessErrorsResponses[keyof GetProcessErrorsResponses];

export type GetProcessLogsData = {
    body?: never;
    path: {
        /**
         * Process name to get logs for
         */
        processName: string;
    };
    query?: never;
    url: '/computeruse/process/{processName}/logs';
};

export type GetProcessLogsResponses = {
    /**
     * OK
     */
    200: ProcessLogsResponse;
};

export type GetProcessLogsResponse = GetProcessLogsResponses[keyof GetProcessLogsResponses];

export type RestartProcessData = {
    body?: never;
    path: {
        /**
         * Process name to restart
         */
        processName: string;
    };
    query?: never;
    url: '/computeruse/process/{processName}/restart';
};

export type RestartProcessResponses = {
    /**
     * OK
     */
    200: ProcessRestartResponse;
};

export type RestartProcessResponse = RestartProcessResponses[keyof RestartProcessResponses];

export type GetProcessStatusData = {
    body?: never;
    path: {
        /**
         * Process name to check
         */
        processName: string;
    };
    query?: never;
    url: '/computeruse/process/{processName}/status';
};

export type GetProcessStatusResponses = {
    /**
     * OK
     */
    200: ProcessStatusResponse;
};

export type GetProcessStatusResponse = GetProcessStatusResponses[keyof GetProcessStatusResponses];

export type ListRecordingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/recordings';
};

export type ListRecordingsErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type ListRecordingsError = ListRecordingsErrors[keyof ListRecordingsErrors];

export type ListRecordingsResponses = {
    /**
     * OK
     */
    200: ListRecordingsResponse;
};

export type ListRecordingsResponse2 = ListRecordingsResponses[keyof ListRecordingsResponses];

export type StartRecordingData = {
    /**
     * Recording options
     */
    body?: StartRecordingRequest;
    path?: never;
    query?: never;
    url: '/computeruse/recordings/start';
};

export type StartRecordingErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type StartRecordingError = StartRecordingErrors[keyof StartRecordingErrors];

export type StartRecordingResponses = {
    /**
     * Created
     */
    201: Recording;
};

export type StartRecordingResponse = StartRecordingResponses[keyof StartRecordingResponses];

export type StopRecordingData = {
    /**
     * Recording ID to stop
     */
    body: StopRecordingRequest;
    path?: never;
    query?: never;
    url: '/computeruse/recordings/stop';
};

export type StopRecordingErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type StopRecordingError = StopRecordingErrors[keyof StopRecordingErrors];

export type StopRecordingResponses = {
    /**
     * OK
     */
    200: Recording;
};

export type StopRecordingResponse = StopRecordingResponses[keyof StopRecordingResponses];

export type DeleteRecordingData = {
    body?: never;
    path: {
        /**
         * Recording ID
         */
        id: string;
    };
    query?: never;
    url: '/computeruse/recordings/{id}';
};

export type DeleteRecordingErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DeleteRecordingError = DeleteRecordingErrors[keyof DeleteRecordingErrors];

export type DeleteRecordingResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetRecordingData = {
    body?: never;
    path: {
        /**
         * Recording ID
         */
        id: string;
    };
    query?: never;
    url: '/computeruse/recordings/{id}';
};

export type GetRecordingErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetRecordingError = GetRecordingErrors[keyof GetRecordingErrors];

export type GetRecordingResponses = {
    /**
     * OK
     */
    200: Recording;
};

export type GetRecordingResponse = GetRecordingResponses[keyof GetRecordingResponses];

export type DownloadRecordingData = {
    body?: never;
    path: {
        /**
         * Recording ID
         */
        id: string;
    };
    query?: never;
    url: '/computeruse/recordings/{id}/download';
};

export type DownloadRecordingErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type DownloadRecordingError = DownloadRecordingErrors[keyof DownloadRecordingErrors];

export type DownloadRecordingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TakeScreenshotData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Whether to show cursor in screenshot
         */
        showCursor?: boolean;
    };
    url: '/computeruse/screenshot';
};

export type TakeScreenshotResponses = {
    /**
     * OK
     */
    200: ScreenshotResponse;
};

export type TakeScreenshotResponse = TakeScreenshotResponses[keyof TakeScreenshotResponses];

export type TakeCompressedScreenshotData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Whether to show cursor in screenshot
         */
        showCursor?: boolean;
        /**
         * Image format (png or jpeg)
         */
        format?: string;
        /**
         * JPEG quality (1-100)
         */
        quality?: number;
        /**
         * Scale factor (0.1-1.0)
         */
        scale?: number;
    };
    url: '/computeruse/screenshot/compressed';
};

export type TakeCompressedScreenshotResponses = {
    /**
     * OK
     */
    200: ScreenshotResponse;
};

export type TakeCompressedScreenshotResponse = TakeCompressedScreenshotResponses[keyof TakeCompressedScreenshotResponses];

export type TakeRegionScreenshotData = {
    body?: never;
    path?: never;
    query: {
        /**
         * X coordinate of the region
         */
        x: number;
        /**
         * Y coordinate of the region
         */
        y: number;
        /**
         * Width of the region
         */
        width: number;
        /**
         * Height of the region
         */
        height: number;
        /**
         * Whether to show cursor in screenshot
         */
        showCursor?: boolean;
    };
    url: '/computeruse/screenshot/region';
};

export type TakeRegionScreenshotResponses = {
    /**
     * OK
     */
    200: ScreenshotResponse;
};

export type TakeRegionScreenshotResponse = TakeRegionScreenshotResponses[keyof TakeRegionScreenshotResponses];

export type TakeCompressedRegionScreenshotData = {
    body?: never;
    path?: never;
    query: {
        /**
         * X coordinate of the region
         */
        x: number;
        /**
         * Y coordinate of the region
         */
        y: number;
        /**
         * Width of the region
         */
        width: number;
        /**
         * Height of the region
         */
        height: number;
        /**
         * Whether to show cursor in screenshot
         */
        showCursor?: boolean;
        /**
         * Image format (png or jpeg)
         */
        format?: string;
        /**
         * JPEG quality (1-100)
         */
        quality?: number;
        /**
         * Scale factor (0.1-1.0)
         */
        scale?: number;
    };
    url: '/computeruse/screenshot/region/compressed';
};

export type TakeCompressedRegionScreenshotResponses = {
    /**
     * OK
     */
    200: ScreenshotResponse;
};

export type TakeCompressedRegionScreenshotResponse = TakeCompressedRegionScreenshotResponses[keyof TakeCompressedRegionScreenshotResponses];

export type StartComputerUseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/start';
};

export type StartComputerUseResponses = {
    /**
     * OK
     */
    200: ComputerUseStartResponse;
};

export type StartComputerUseResponse = StartComputerUseResponses[keyof StartComputerUseResponses];

export type GetComputerUseSystemStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/status';
};

export type GetComputerUseSystemStatusResponses = {
    /**
     * OK
     */
    200: ComputerUseStatusResponse;
};

export type GetComputerUseSystemStatusResponse = GetComputerUseSystemStatusResponses[keyof GetComputerUseSystemStatusResponses];

export type StopComputerUseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/computeruse/stop';
};

export type StopComputerUseResponses = {
    /**
     * OK
     */
    200: ComputerUseStopResponse;
};

export type StopComputerUseResponse = StopComputerUseResponses[keyof StopComputerUseResponses];

export type DeleteFileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File or directory path to delete
         */
        path: string;
        /**
         * Enable recursive deletion for directories
         */
        recursive?: boolean;
    };
    url: '/files';
};

export type DeleteFileResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Directory path to list (defaults to working directory)
         */
        path?: string;
    };
    url: '/files';
};

export type ListFilesResponses = {
    /**
     * OK
     */
    200: Array<FileInfo>;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type DownloadFilesData = {
    /**
     * Paths of files to download
     */
    body: FilesDownloadRequest;
    path?: never;
    query?: never;
    url: '/files/bulk-download';
};

export type DownloadFilesResponses = {
    /**
     * OK
     */
    200: GinH;
};

export type DownloadFilesResponse = DownloadFilesResponses[keyof DownloadFilesResponses];

export type UploadFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/files/bulk-upload';
};

export type UploadFilesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DownloadFileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File path to download
         */
        path: string;
    };
    url: '/files/download';
};

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindInFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Directory path to search in
         */
        path: string;
        /**
         * Text pattern to search for
         */
        pattern: string;
    };
    url: '/files/find';
};

export type FindInFilesResponses = {
    /**
     * OK
     */
    200: Array<Match>;
};

export type FindInFilesResponse = FindInFilesResponses[keyof FindInFilesResponses];

export type CreateFolderData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Folder path to create
         */
        path: string;
        /**
         * Octal permission mode (default: 0755)
         */
        mode: string;
    };
    url: '/files/folder';
};

export type CreateFolderResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetFileInfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File or directory path
         */
        path: string;
    };
    url: '/files/info';
};

export type GetFileInfoResponses = {
    /**
     * OK
     */
    200: FileInfo;
};

export type GetFileInfoResponse = GetFileInfoResponses[keyof GetFileInfoResponses];

export type MoveFileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Source file or directory path
         */
        source: string;
        /**
         * Destination file or directory path
         */
        destination: string;
    };
    url: '/files/move';
};

export type MoveFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetFilePermissionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File or directory path
         */
        path: string;
        /**
         * Owner (username or UID)
         */
        owner?: string;
        /**
         * Group (group name or GID)
         */
        group?: string;
        /**
         * File mode in octal format (e.g., 0755)
         */
        mode?: string;
    };
    url: '/files/permissions';
};

export type SetFilePermissionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReplaceInFilesData = {
    /**
     * Replace request
     */
    body: ReplaceRequest;
    path?: never;
    query?: never;
    url: '/files/replace';
};

export type ReplaceInFilesResponses = {
    /**
     * OK
     */
    200: Array<ReplaceResult>;
};

export type ReplaceInFilesResponse = ReplaceInFilesResponses[keyof ReplaceInFilesResponses];

export type SearchFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Directory path to search in
         */
        path: string;
        /**
         * File pattern to match (e.g., *.txt, *.go)
         */
        pattern: string;
    };
    url: '/files/search';
};

export type SearchFilesResponses = {
    /**
     * OK
     */
    200: SearchFilesResponse;
};

export type SearchFilesResponse2 = SearchFilesResponses[keyof SearchFilesResponses];

export type UploadFileData = {
    body: {
        /**
         * File to upload
         */
        file: Blob | File;
    };
    path?: never;
    query: {
        /**
         * Destination path for the uploaded file
         */
        path: string;
    };
    url: '/files/upload';
};

export type UploadFileResponses = {
    /**
     * OK
     */
    200: GinH;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type AddFilesData = {
    /**
     * Add files request
     */
    body: GitAddRequest;
    path?: never;
    query?: never;
    url: '/git/add';
};

export type AddFilesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteBranchData = {
    /**
     * Delete branch request
     */
    body: GitGitDeleteBranchRequest;
    path?: never;
    query?: never;
    url: '/git/branches';
};

export type DeleteBranchResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type ListBranchesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repository path
         */
        path: string;
    };
    url: '/git/branches';
};

export type ListBranchesResponses = {
    /**
     * OK
     */
    200: ListBranchResponse;
};

export type ListBranchesResponse = ListBranchesResponses[keyof ListBranchesResponses];

export type CreateBranchData = {
    /**
     * Create branch request
     */
    body: GitBranchRequest;
    path?: never;
    query?: never;
    url: '/git/branches';
};

export type CreateBranchResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type CheckoutBranchData = {
    /**
     * Checkout request
     */
    body: GitCheckoutRequest;
    path?: never;
    query?: never;
    url: '/git/checkout';
};

export type CheckoutBranchResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CloneRepositoryData = {
    /**
     * Clone repository request
     */
    body: GitCloneRequest;
    path?: never;
    query?: never;
    url: '/git/clone';
};

export type CloneRepositoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CommitChangesData = {
    /**
     * Commit request
     */
    body: GitCommitRequest;
    path?: never;
    query?: never;
    url: '/git/commit';
};

export type CommitChangesResponses = {
    /**
     * OK
     */
    200: GitCommitResponse;
};

export type CommitChangesResponse = CommitChangesResponses[keyof CommitChangesResponses];

export type GetCommitHistoryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repository path
         */
        path: string;
    };
    url: '/git/history';
};

export type GetCommitHistoryResponses = {
    /**
     * OK
     */
    200: Array<GitCommitInfo>;
};

export type GetCommitHistoryResponse = GetCommitHistoryResponses[keyof GetCommitHistoryResponses];

export type PullChangesData = {
    /**
     * Pull request
     */
    body: GitRepoRequest;
    path?: never;
    query?: never;
    url: '/git/pull';
};

export type PullChangesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PushChangesData = {
    /**
     * Push request
     */
    body: GitRepoRequest;
    path?: never;
    query?: never;
    url: '/git/push';
};

export type PushChangesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repository path
         */
        path: string;
    };
    url: '/git/status';
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: GitStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type CompletionsData = {
    /**
     * Completion request
     */
    body: LspCompletionParams;
    path?: never;
    query?: never;
    url: '/lsp/completions';
};

export type CompletionsResponses = {
    /**
     * OK
     */
    200: CompletionList;
};

export type CompletionsResponse = CompletionsResponses[keyof CompletionsResponses];

export type DidCloseData = {
    /**
     * Document request
     */
    body: LspDocumentRequest;
    path?: never;
    query?: never;
    url: '/lsp/did-close';
};

export type DidCloseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DidOpenData = {
    /**
     * Document request
     */
    body: LspDocumentRequest;
    path?: never;
    query?: never;
    url: '/lsp/did-open';
};

export type DidOpenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentSymbolsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Language ID (e.g., python, typescript)
         */
        languageId: string;
        /**
         * Path to project
         */
        pathToProject: string;
        /**
         * Document URI
         */
        uri: string;
    };
    url: '/lsp/document-symbols';
};

export type DocumentSymbolsResponses = {
    /**
     * OK
     */
    200: Array<LspSymbol>;
};

export type DocumentSymbolsResponse = DocumentSymbolsResponses[keyof DocumentSymbolsResponses];

export type StartData = {
    /**
     * LSP server request
     */
    body: LspServerRequest;
    path?: never;
    query?: never;
    url: '/lsp/start';
};

export type StartResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StopData = {
    /**
     * LSP server request
     */
    body: LspServerRequest;
    path?: never;
    query?: never;
    url: '/lsp/stop';
};

export type StopResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type WorkspaceSymbolsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query
         */
        query: string;
        /**
         * Language ID (e.g., python, typescript)
         */
        languageId: string;
        /**
         * Path to project
         */
        pathToProject: string;
    };
    url: '/lsp/workspacesymbols';
};

export type WorkspaceSymbolsResponses = {
    /**
     * OK
     */
    200: Array<LspSymbol>;
};

export type WorkspaceSymbolsResponse = WorkspaceSymbolsResponses[keyof WorkspaceSymbolsResponses];

export type GetPortsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/port';
};

export type GetPortsResponses = {
    /**
     * OK
     */
    200: PortList;
};

export type GetPortsResponse = GetPortsResponses[keyof GetPortsResponses];

export type IsPortInUseData = {
    body?: never;
    path: {
        /**
         * Port number (3000-9999)
         */
        port: number;
    };
    query?: never;
    url: '/port/{port}/in-use';
};

export type IsPortInUseResponses = {
    /**
     * OK
     */
    200: IsPortInUseResponse;
};

export type IsPortInUseResponse2 = IsPortInUseResponses[keyof IsPortInUseResponses];

export type ExecuteCommandData = {
    /**
     * Command execution request
     */
    body: ExecuteRequest;
    path?: never;
    query?: never;
    url: '/process/execute';
};

export type ExecuteCommandResponses = {
    /**
     * OK
     */
    200: ExecuteResponse;
};

export type ExecuteCommandResponse = ExecuteCommandResponses[keyof ExecuteCommandResponses];

export type ListInterpreterContextsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/process/interpreter/context';
};

export type ListInterpreterContextsResponses = {
    /**
     * OK
     */
    200: ListContextsResponse;
};

export type ListInterpreterContextsResponse = ListInterpreterContextsResponses[keyof ListInterpreterContextsResponses];

export type CreateInterpreterContextData = {
    /**
     * Context configuration
     */
    body: CreateContextRequest;
    path?: never;
    query?: never;
    url: '/process/interpreter/context';
};

export type CreateInterpreterContextErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type CreateInterpreterContextError = CreateInterpreterContextErrors[keyof CreateInterpreterContextErrors];

export type CreateInterpreterContextResponses = {
    /**
     * OK
     */
    200: InterpreterContext;
};

export type CreateInterpreterContextResponse = CreateInterpreterContextResponses[keyof CreateInterpreterContextResponses];

export type DeleteInterpreterContextData = {
    body?: never;
    path: {
        /**
         * Context ID
         */
        id: string;
    };
    query?: never;
    url: '/process/interpreter/context/{id}';
};

export type DeleteInterpreterContextErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type DeleteInterpreterContextError = DeleteInterpreterContextErrors[keyof DeleteInterpreterContextErrors];

export type DeleteInterpreterContextResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteInterpreterContextResponse = DeleteInterpreterContextResponses[keyof DeleteInterpreterContextResponses];

export type ExecuteInterpreterCodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/process/interpreter/execute';
};

export type ListPtySessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/process/pty';
};

export type ListPtySessionsResponses = {
    /**
     * OK
     */
    200: PtyListResponse;
};

export type ListPtySessionsResponse = ListPtySessionsResponses[keyof ListPtySessionsResponses];

export type CreatePtySessionData = {
    /**
     * PTY session creation request
     */
    body: PtyCreateRequest;
    path?: never;
    query?: never;
    url: '/process/pty';
};

export type CreatePtySessionResponses = {
    /**
     * Created
     */
    201: PtyCreateResponse;
};

export type CreatePtySessionResponse = CreatePtySessionResponses[keyof CreatePtySessionResponses];

export type DeletePtySessionData = {
    body?: never;
    path: {
        /**
         * PTY session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/pty/{sessionId}';
};

export type DeletePtySessionResponses = {
    /**
     * OK
     */
    200: GinH;
};

export type DeletePtySessionResponse = DeletePtySessionResponses[keyof DeletePtySessionResponses];

export type GetPtySessionData = {
    body?: never;
    path: {
        /**
         * PTY session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/pty/{sessionId}';
};

export type GetPtySessionResponses = {
    /**
     * OK
     */
    200: PtySessionInfo;
};

export type GetPtySessionResponse = GetPtySessionResponses[keyof GetPtySessionResponses];

export type ConnectPtySessionData = {
    body?: never;
    path: {
        /**
         * PTY session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/pty/{sessionId}/connect';
};

export type ResizePtySessionData = {
    /**
     * Resize request with new dimensions
     */
    body: PtyResizeRequest;
    path: {
        /**
         * PTY session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/pty/{sessionId}/resize';
};

export type ResizePtySessionResponses = {
    /**
     * OK
     */
    200: PtySessionInfo;
};

export type ResizePtySessionResponse = ResizePtySessionResponses[keyof ResizePtySessionResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/process/session';
};

export type ListSessionsResponses = {
    /**
     * OK
     */
    200: Array<Session>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type CreateSessionData = {
    /**
     * Session creation request
     */
    body: CreateSessionRequest;
    path?: never;
    query?: never;
    url: '/process/session';
};

export type CreateSessionResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteSessionData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/session/{sessionId}';
};

export type DeleteSessionResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetSessionData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/session/{sessionId}';
};

export type GetSessionResponses = {
    /**
     * OK
     */
    200: Session;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type GetSessionCommandData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
        /**
         * Command ID
         */
        commandId: string;
    };
    query?: never;
    url: '/process/session/{sessionId}/command/{commandId}';
};

export type GetSessionCommandResponses = {
    /**
     * OK
     */
    200: Command;
};

export type GetSessionCommandResponse = GetSessionCommandResponses[keyof GetSessionCommandResponses];

export type SendInputData = {
    /**
     * Input send request
     */
    body: SessionSendInputRequest;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
        /**
         * Command ID
         */
        commandId: string;
    };
    query?: never;
    url: '/process/session/{sessionId}/command/{commandId}/input';
};

export type SendInputResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetSessionCommandLogsData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
        /**
         * Command ID
         */
        commandId: string;
    };
    query?: {
        /**
         * Follow logs in real-time (WebSocket only)
         */
        follow?: boolean;
    };
    url: '/process/session/{sessionId}/command/{commandId}/logs';
};

export type GetSessionCommandLogsResponses = {
    /**
     * Log content
     */
    200: string;
};

export type GetSessionCommandLogsResponse = GetSessionCommandLogsResponses[keyof GetSessionCommandLogsResponses];

export type SessionExecuteCommandData = {
    /**
     * Command execution request
     */
    body: SessionExecuteRequest;
    path: {
        /**
         * Session ID
         */
        sessionId: string;
    };
    query?: never;
    url: '/process/session/{sessionId}/exec';
};

export type SessionExecuteCommandResponses = {
    /**
     * OK
     */
    200: SessionExecuteResponse;
    /**
     * Accepted
     */
    202: SessionExecuteResponse;
};

export type SessionExecuteCommandResponse = SessionExecuteCommandResponses[keyof SessionExecuteCommandResponses];

export type GetUserHomeDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-home-dir';
};

export type GetUserHomeDirResponses = {
    /**
     * OK
     */
    200: UserHomeDirResponse;
};

export type GetUserHomeDirResponse = GetUserHomeDirResponses[keyof GetUserHomeDirResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type GetWorkDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/work-dir';
};

export type GetWorkDirResponses = {
    /**
     * OK
     */
    200: WorkDirResponse;
};

export type GetWorkDirResponse = GetWorkDirResponses[keyof GetWorkDirResponses];
