// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCommand = z.object({
    command: z.string(),
    exitCode: z.optional(z.int()),
    id: z.string()
});

export const zCompletionContext = z.object({
    triggerCharacter: z.optional(z.string()),
    triggerKind: z.int()
});

export const zCompletionItem = z.object({
    detail: z.optional(z.string()),
    documentation: z.optional(z.unknown()),
    filterText: z.optional(z.string()),
    insertText: z.optional(z.string()),
    kind: z.optional(z.int()),
    label: z.string(),
    sortText: z.optional(z.string())
});

export const zCompletionList = z.object({
    isIncomplete: z.boolean(),
    items: z.array(zCompletionItem)
});

export const zComputerUseStatusResponse = z.object({
    status: z.optional(z.string())
});

export const zCreateContextRequest = z.object({
    cwd: z.optional(z.string()),
    language: z.optional(z.string())
});

export const zCreateSessionRequest = z.object({
    sessionId: z.string()
});

export const zDisplayInfo = z.object({
    height: z.optional(z.int()),
    id: z.optional(z.int()),
    isActive: z.optional(z.boolean()),
    width: z.optional(z.int()),
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zDisplayInfoResponse = z.object({
    displays: z.optional(z.array(zDisplayInfo))
});

export const zEmpty = z.record(z.string(), z.unknown());

export const zExecuteRequest = z.object({
    command: z.string(),
    cwd: z.optional(z.string()),
    timeout: z.optional(z.int())
});

export const zExecuteResponse = z.object({
    exitCode: z.optional(z.int()),
    result: z.string()
});

export const zFileInfo = z.object({
    group: z.string(),
    isDir: z.boolean(),
    modTime: z.string(),
    mode: z.string(),
    name: z.string(),
    owner: z.string(),
    permissions: z.string(),
    size: z.int()
});

export const zFilesDownloadRequest = z.object({
    paths: z.array(z.string())
});

export const zGitAddRequest = z.object({
    files: z.array(z.string()),
    path: z.string()
});

export const zGitBranchRequest = z.object({
    name: z.string(),
    path: z.string()
});

export const zGitCheckoutRequest = z.object({
    branch: z.string(),
    path: z.string()
});

export const zGitCloneRequest = z.object({
    branch: z.optional(z.string()),
    commit_id: z.optional(z.string()),
    password: z.optional(z.string()),
    path: z.string(),
    url: z.string(),
    username: z.optional(z.string())
});

export const zGitCommitInfo = z.object({
    author: z.string(),
    email: z.string(),
    hash: z.string(),
    message: z.string(),
    timestamp: z.string()
});

export const zGitCommitRequest = z.object({
    allow_empty: z.optional(z.boolean()),
    author: z.string(),
    email: z.string(),
    message: z.string(),
    path: z.string()
});

export const zGitCommitResponse = z.object({
    hash: z.string()
});

export const zGitRepoRequest = z.object({
    password: z.optional(z.string()),
    path: z.string(),
    username: z.optional(z.string())
});

export const zInterpreterContext = z.object({
    active: z.boolean(),
    createdAt: z.string(),
    cwd: z.string(),
    id: z.string(),
    language: z.string()
});

export const zIsPortInUseResponse = z.object({
    isInUse: z.optional(z.boolean())
});

export const zKeyboardHotkeyRequest = z.object({
    keys: z.optional(z.string())
});

export const zKeyboardPressRequest = z.object({
    key: z.optional(z.string()),
    modifiers: z.optional(z.array(z.string()))
});

export const zKeyboardTypeRequest = z.object({
    delay: z.optional(z.int()),
    text: z.optional(z.string())
});

export const zListBranchResponse = z.object({
    branches: z.array(z.string())
});

export const zListContextsResponse = z.object({
    contexts: z.array(zInterpreterContext)
});

export const zLspDocumentRequest = z.object({
    languageId: z.string(),
    pathToProject: z.string(),
    uri: z.string()
});

export const zLspPosition = z.object({
    character: z.int(),
    line: z.int()
});

export const zLspCompletionParams = z.object({
    context: z.optional(zCompletionContext),
    languageId: z.string(),
    pathToProject: z.string(),
    position: zLspPosition,
    uri: z.string()
});

export const zLspRange = z.object({
    end: zLspPosition,
    start: zLspPosition
});

export const zLspLocation = z.object({
    range: zLspRange,
    uri: z.string()
});

export const zLspServerRequest = z.object({
    languageId: z.string(),
    pathToProject: z.string()
});

export const zLspSymbol = z.object({
    kind: z.int(),
    location: zLspLocation,
    name: z.string()
});

export const zMatch = z.object({
    content: z.string(),
    file: z.string(),
    line: z.int()
});

export const zMouseClickRequest = z.object({
    button: z.optional(z.string()),
    double: z.optional(z.boolean()),
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zMouseClickResponse = z.object({
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zMouseDragRequest = z.object({
    button: z.optional(z.string()),
    endX: z.optional(z.int()),
    endY: z.optional(z.int()),
    startX: z.optional(z.int()),
    startY: z.optional(z.int())
});

export const zMouseDragResponse = z.object({
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zMouseMoveRequest = z.object({
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zMousePositionResponse = z.object({
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zMouseScrollRequest = z.object({
    amount: z.optional(z.int()),
    direction: z.optional(z.string()),
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zPortList = z.object({
    ports: z.optional(z.array(z.int()))
});

export const zPosition = z.object({
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zProcessErrorsResponse = z.object({
    errors: z.optional(z.string()),
    processName: z.optional(z.string())
});

export const zProcessLogsResponse = z.object({
    logs: z.optional(z.string()),
    processName: z.optional(z.string())
});

export const zProcessRestartResponse = z.object({
    message: z.optional(z.string()),
    processName: z.optional(z.string())
});

export const zProcessStatus = z.object({
    autoRestart: z.optional(z.boolean()),
    pid: z.optional(z.int()),
    priority: z.optional(z.int()),
    running: z.optional(z.boolean())
});

export const zComputerUseStartResponse = z.object({
    message: z.optional(z.string()),
    status: z.optional(z.record(z.string(), zProcessStatus))
});

export const zComputerUseStopResponse = z.object({
    message: z.optional(z.string()),
    status: z.optional(z.record(z.string(), zProcessStatus))
});

export const zProcessStatusResponse = z.object({
    processName: z.optional(z.string()),
    running: z.optional(z.boolean())
});

export const zPtyCreateRequest = z.object({
    cols: z.optional(z.int()),
    cwd: z.optional(z.string()),
    envs: z.optional(z.record(z.string(), z.string())),
    id: z.optional(z.string()),
    lazyStart: z.optional(z.boolean()),
    rows: z.optional(z.int())
});

export const zPtyCreateResponse = z.object({
    sessionId: z.string()
});

export const zPtyResizeRequest = z.object({
    cols: z.int().gte(1).lte(1000),
    rows: z.int().gte(1).lte(1000)
});

export const zPtySessionInfo = z.object({
    active: z.boolean(),
    cols: z.int(),
    createdAt: z.string(),
    cwd: z.string(),
    envs: z.record(z.string(), z.string()),
    id: z.string(),
    lazyStart: z.boolean(),
    rows: z.int()
});

export const zPtyListResponse = z.object({
    sessions: z.array(zPtySessionInfo)
});

export const zRecording = z.object({
    durationSeconds: z.optional(z.number()),
    endTime: z.optional(z.string()),
    fileName: z.string(),
    filePath: z.string(),
    id: z.string(),
    sizeBytes: z.optional(z.int()),
    startTime: z.string(),
    status: z.string()
});

export const zListRecordingsResponse = z.object({
    recordings: z.array(zRecording)
});

export const zReplaceRequest = z.object({
    files: z.array(z.string()),
    newValue: z.string(),
    pattern: z.string()
});

export const zReplaceResult = z.object({
    error: z.optional(z.string()),
    file: z.optional(z.string()),
    success: z.optional(z.boolean())
});

export const zScreenshotResponse = z.object({
    cursorPosition: z.optional(zPosition),
    screenshot: z.optional(z.string()),
    sizeBytes: z.optional(z.int())
});

export const zScrollResponse = z.object({
    success: z.optional(z.boolean())
});

export const zSearchFilesResponse = z.object({
    files: z.array(z.string())
});

export const zSession = z.object({
    commands: z.array(zCommand),
    sessionId: z.string()
});

export const zSessionExecuteRequest = z.object({
    async: z.optional(z.boolean()),
    command: z.string(),
    runAsync: z.optional(z.boolean())
});

export const zSessionExecuteResponse = z.object({
    cmdId: z.string(),
    exitCode: z.optional(z.int()),
    output: z.optional(z.string()),
    stderr: z.optional(z.string()),
    stdout: z.optional(z.string())
});

export const zSessionSendInputRequest = z.object({
    data: z.string()
});

export const zStartRecordingRequest = z.object({
    label: z.optional(z.string())
});

export const zStatus = z.enum([
    'Unmodified',
    'Untracked',
    'Modified',
    'Added',
    'Deleted',
    'Renamed',
    'Copied',
    'Updated but unmerged'
]);

export const zFileStatus = z.object({
    extra: z.string(),
    name: z.string(),
    staging: zStatus,
    worktree: zStatus
});

export const zGitStatus = z.object({
    ahead: z.optional(z.int()),
    behind: z.optional(z.int()),
    branchPublished: z.optional(z.boolean()),
    currentBranch: z.string(),
    fileStatus: z.array(zFileStatus)
});

export const zStopRecordingRequest = z.object({
    id: z.string()
});

export const zUserHomeDirResponse = z.object({
    dir: z.string()
});

export const zWindowInfo = z.object({
    height: z.optional(z.int()),
    id: z.optional(z.int()),
    isActive: z.optional(z.boolean()),
    title: z.optional(z.string()),
    width: z.optional(z.int()),
    x: z.optional(z.int()),
    y: z.optional(z.int())
});

export const zWindowsResponse = z.object({
    windows: z.optional(z.array(zWindowInfo))
});

export const zWorkDirResponse = z.object({
    dir: z.string()
});

export const zGinH = z.record(z.string(), z.unknown());

export const zGitGitDeleteBranchRequest = z.object({
    name: z.string(),
    path: z.string()
});

export const zGetDisplayInfoData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDisplayInfoResponse = zDisplayInfoResponse;

export const zGetWindowsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetWindowsResponse = zWindowsResponse;

export const zPressHotkeyData = z.object({
    body: zKeyboardHotkeyRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPressHotkeyResponse = zEmpty;

export const zPressKeyData = z.object({
    body: zKeyboardPressRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPressKeyResponse = zEmpty;

export const zTypeTextData = z.object({
    body: zKeyboardTypeRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zTypeTextResponse = zEmpty;

export const zClickData = z.object({
    body: zMouseClickRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zClickResponse = zMouseClickResponse;

export const zDragData = z.object({
    body: zMouseDragRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDragResponse = zMouseDragResponse;

export const zMoveMouseData = z.object({
    body: zMouseMoveRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zMoveMouseResponse = zMousePositionResponse;

export const zGetMousePositionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetMousePositionResponse = zMousePositionResponse;

export const zScrollData = z.object({
    body: zMouseScrollRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zScrollResponse2 = zScrollResponse;

export const zGetComputerUseStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetComputerUseStatusResponse = zComputerUseStatusResponse;

export const zGetProcessErrorsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        processName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProcessErrorsResponse = zProcessErrorsResponse;

export const zGetProcessLogsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        processName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProcessLogsResponse = zProcessLogsResponse;

export const zRestartProcessData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        processName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zRestartProcessResponse = zProcessRestartResponse;

export const zGetProcessStatusData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        processName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProcessStatusResponse = zProcessStatusResponse;

export const zListRecordingsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListRecordingsResponse2 = zListRecordingsResponse;

export const zStartRecordingData = z.object({
    body: z.optional(zStartRecordingRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zStartRecordingResponse = zRecording;

export const zStopRecordingData = z.object({
    body: zStopRecordingRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zStopRecordingResponse = zRecording;

export const zDeleteRecordingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetRecordingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetRecordingResponse = zRecording;

export const zDownloadRecordingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zTakeScreenshotData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        showCursor: z.optional(z.boolean())
    }))
});

/**
 * OK
 */
export const zTakeScreenshotResponse = zScreenshotResponse;

export const zTakeCompressedScreenshotData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        showCursor: z.optional(z.boolean()),
        format: z.optional(z.string()),
        quality: z.optional(z.int()),
        scale: z.optional(z.number())
    }))
});

/**
 * OK
 */
export const zTakeCompressedScreenshotResponse = zScreenshotResponse;

export const zTakeRegionScreenshotData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        x: z.int(),
        y: z.int(),
        width: z.int(),
        height: z.int(),
        showCursor: z.optional(z.boolean())
    })
});

/**
 * OK
 */
export const zTakeRegionScreenshotResponse = zScreenshotResponse;

export const zTakeCompressedRegionScreenshotData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        x: z.int(),
        y: z.int(),
        width: z.int(),
        height: z.int(),
        showCursor: z.optional(z.boolean()),
        format: z.optional(z.string()),
        quality: z.optional(z.int()),
        scale: z.optional(z.number())
    })
});

/**
 * OK
 */
export const zTakeCompressedRegionScreenshotResponse = zScreenshotResponse;

export const zStartComputerUseData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zStartComputerUseResponse = zComputerUseStartResponse;

export const zGetComputerUseSystemStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetComputerUseSystemStatusResponse = zComputerUseStatusResponse;

export const zStopComputerUseData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zStopComputerUseResponse = zComputerUseStopResponse;

export const zDeleteFileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string(),
        recursive: z.optional(z.boolean())
    })
});

export const zListFilesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        path: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zListFilesResponse = z.array(zFileInfo);

export const zDownloadFilesData = z.object({
    body: zFilesDownloadRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDownloadFilesResponse = zGinH;

export const zUploadFilesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDownloadFileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

export const zFindInFilesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string(),
        pattern: z.string()
    })
});

/**
 * OK
 */
export const zFindInFilesResponse = z.array(zMatch);

export const zCreateFolderData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string(),
        mode: z.string()
    })
});

export const zGetFileInfoData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

/**
 * OK
 */
export const zGetFileInfoResponse = zFileInfo;

export const zMoveFileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        source: z.string(),
        destination: z.string()
    })
});

export const zSetFilePermissionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string(),
        owner: z.optional(z.string()),
        group: z.optional(z.string()),
        mode: z.optional(z.string())
    })
});

export const zReplaceInFilesData = z.object({
    body: zReplaceRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zReplaceInFilesResponse = z.array(zReplaceResult);

export const zSearchFilesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string(),
        pattern: z.string()
    })
});

/**
 * OK
 */
export const zSearchFilesResponse2 = zSearchFilesResponse;

export const zUploadFileData = z.object({
    body: z.object({
        file: z.string()
    }),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

/**
 * OK
 */
export const zUploadFileResponse = zGinH;

export const zAddFilesData = z.object({
    body: zGitAddRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteBranchData = z.object({
    body: zGitGitDeleteBranchRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zListBranchesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

/**
 * OK
 */
export const zListBranchesResponse = zListBranchResponse;

export const zCreateBranchData = z.object({
    body: zGitBranchRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCheckoutBranchData = z.object({
    body: zGitCheckoutRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCloneRepositoryData = z.object({
    body: zGitCloneRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCommitChangesData = z.object({
    body: zGitCommitRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCommitChangesResponse = zGitCommitResponse;

export const zGetCommitHistoryData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

/**
 * OK
 */
export const zGetCommitHistoryResponse = z.array(zGitCommitInfo);

export const zPullChangesData = z.object({
    body: zGitRepoRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPushChangesData = z.object({
    body: zGitRepoRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        path: z.string()
    })
});

/**
 * OK
 */
export const zGetStatusResponse = zGitStatus;

export const zCompletionsData = z.object({
    body: zLspCompletionParams,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCompletionsResponse = zCompletionList;

export const zDidCloseData = z.object({
    body: zLspDocumentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDidOpenData = z.object({
    body: zLspDocumentRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDocumentSymbolsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        languageId: z.string(),
        pathToProject: z.string(),
        uri: z.string()
    })
});

/**
 * OK
 */
export const zDocumentSymbolsResponse = z.array(zLspSymbol);

export const zStartData = z.object({
    body: zLspServerRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStopData = z.object({
    body: zLspServerRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zWorkspaceSymbolsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        query: z.string(),
        languageId: z.string(),
        pathToProject: z.string()
    })
});

/**
 * OK
 */
export const zWorkspaceSymbolsResponse = z.array(zLspSymbol);

export const zGetPortsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetPortsResponse = zPortList;

export const zIsPortInUseData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        port: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zIsPortInUseResponse2 = zIsPortInUseResponse;

export const zExecuteCommandData = z.object({
    body: zExecuteRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zExecuteCommandResponse = zExecuteResponse;

export const zListInterpreterContextsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListInterpreterContextsResponse = zListContextsResponse;

export const zCreateInterpreterContextData = z.object({
    body: zCreateContextRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCreateInterpreterContextResponse = zInterpreterContext;

export const zDeleteInterpreterContextData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeleteInterpreterContextResponse = z.record(z.string(), z.string());

export const zExecuteInterpreterCodeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zListPtySessionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListPtySessionsResponse = zPtyListResponse;

export const zCreatePtySessionData = z.object({
    body: zPtyCreateRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreatePtySessionResponse = zPtyCreateResponse;

export const zDeletePtySessionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeletePtySessionResponse = zGinH;

export const zGetPtySessionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetPtySessionResponse = zPtySessionInfo;

export const zConnectPtySessionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

export const zResizePtySessionData = z.object({
    body: zPtyResizeRequest,
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zResizePtySessionResponse = zPtySessionInfo;

export const zListSessionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListSessionsResponse = z.array(zSession);

export const zCreateSessionData = z.object({
    body: zCreateSessionRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteSessionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetSessionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSessionResponse = zSession;

export const zGetSessionCommandData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string(),
        commandId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSessionCommandResponse = zCommand;

export const zSendInputData = z.object({
    body: zSessionSendInputRequest,
    path: z.object({
        sessionId: z.string(),
        commandId: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetSessionCommandLogsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        sessionId: z.string(),
        commandId: z.string()
    }),
    query: z.optional(z.object({
        follow: z.optional(z.boolean())
    }))
});

/**
 * Log content
 */
export const zGetSessionCommandLogsResponse = z.string();

export const zSessionExecuteCommandData = z.object({
    body: zSessionExecuteRequest,
    path: z.object({
        sessionId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zSessionExecuteCommandResponse = zSessionExecuteResponse;

export const zGetUserHomeDirData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUserHomeDirResponse = zUserHomeDirResponse;

export const zGetVersionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetVersionResponse = z.record(z.string(), z.string());

export const zGetWorkDirData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetWorkDirResponse = zWorkDirResponse;
