apiVersion: apps/v1
kind: Deployment
metadata:
  name: cared-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cared-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cared-api
    spec:
      containers:
        - name: cared-api
          image: caredai/cared-api:latest
          args: ['--port', '3001']
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          envFrom:
            - secretRef:
                name: cared-api-secrets
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
