apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cared

secretGenerator:
  - name: cared-api-secrets
    envs:
      - secrets.env
    files:
      - GITHUB_PRIVATE_KEY=./github-private-key

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: caredai/cared-api
    newName: caredai/cared-api
    newTag: '0.1'

labels:
  - pairs:
      app.kubernetes.io/part-of: cared
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
