apiVersion: v1
kind: Service
metadata:
  name: cared-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cared-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
