import type { ProviderInfo } from '../types'

/**
 * OpenAI provider information including all available models
 */
const openaiProvider: ProviderInfo = {
  id: 'openai',
  name: 'OpenAI',
  icon: 'openai.svg',
  description: 'OpenAI API services including GPT models, embeddings and DALL·E',
  languageModels: [
    {
      id: 'gpt-5',
      name: 'GPT-5',
      description: 'The best model for coding and agentic tasks across domains.',
      contextWindow: 400000,
      maxOutputTokens: 128000,
      inputTokenPrice: '1.25',
      cachedInputTokenPrice: '0.125',
      outputTokenPrice: '10.00',
    },
    {
      id: 'gpt-5-mini',
      name: 'GPT-5 mini',
      description: 'A faster, more cost-efficient version of GPT-5 for well-defined tasks.',
      contextWindow: 400000,
      maxOutputTokens: 128000,
      inputTokenPrice: '0.25',
      cachedInputTokenPrice: '0.025',
      outputTokenPrice: '2.00',
    },
    {
      id: 'gpt-5-nano',
      name: 'GPT-5 nano',
      description: 'Fastest, most cost-efficient version of GPT-5.',
      chargeable: true,
      contextWindow: 400000,
      maxOutputTokens: 128000,
      inputTokenPrice: '0.05',
      cachedInputTokenPrice: '0.005',
      outputTokenPrice: '0.40',
    },
    {
      id: 'gpt-5-chat-latest',
      name: 'GPT-5 Chat',
      description: 'GPT-5 model used in ChatGPT.',
      contextWindow: 400000,
      maxOutputTokens: 128000,
      inputTokenPrice: '1.25',
      cachedInputTokenPrice: '0.125',
      outputTokenPrice: '10.00',
    },
    {
      id: 'gpt-4.1',
      name: 'GPT-4.1',
      description: 'Excels at function calling and instruction following.',
      contextWindow: 1047576,
      maxOutputTokens: 32768,
      inputTokenPrice: '2.00',
      cachedInputTokenPrice: '0.50',
      outputTokenPrice: '8.00',
    },
    {
      id: 'gpt-4.1-mini',
      name: 'GPT-4.1 mini',
      description: 'Balanced for intelligence, speed, and cost.',
      chargeable: true,
      contextWindow: 1047576,
      maxOutputTokens: 32768,
      inputTokenPrice: '0.40',
      cachedInputTokenPrice: '0.10',
      outputTokenPrice: '1.60',
    },
    {
      id: 'gpt-4.1-nano',
      name: 'GPT-4.1 nano',
      description: 'Fastest, most cost-effective GPT-4.1 model.',
      contextWindow: 1047576,
      maxOutputTokens: 32768,
      inputTokenPrice: '0.10',
      cachedInputTokenPrice: '0.025',
      outputTokenPrice: '0.40',
    },
    {
      id: 'gpt-4o',
      name: 'GPT-4o',
      description: 'Fast, intelligent, flexible GPT model.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '2.50',
      cachedInputTokenPrice: '1.25',
      outputTokenPrice: '10.00',
    },
    {
      id: 'gpt-4o-mini',
      name: 'GPT-4o mini',
      description: 'Fast, affordable small model for focused tasks.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '0.15',
      cachedInputTokenPrice: '0.075',
      outputTokenPrice: '0.60',
    },
    /*
    {
      id: 'gpt-4o-audio-preview',
      name: 'GPT-4o Audio',
      description: 'GPT-4o models capable of audio inputs and outputs.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '2.50',
      outputTokenPrice: '10.00'
    },
    {
      id: 'gpt-4o-realtime-preview',
      name: 'GPT-4o Realtime',
      description: 'Model capable of realtime text and audio inputs and outputs.',
      contextWindow: 32000,
      maxOutputTokens: 4096,
      inputTokenPrice: '5.00',
      cachedInputTokenPrice: '2.50',
      outputTokenPrice: '20.00'
    },
    {
      id: 'gpt-4o-mini-audio-preview',
      name: 'GPT-4o mini Audio',
      description: 'Smaller model capable of audio inputs and outputs.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '0.15',
      outputTokenPrice: '0.60'
    },
    {
      id: 'gpt-4o-mini-realtime-preview',
      name: 'GPT-4o mini Realtime',
      description: 'Smaller realtime model for text and audio inputs and outputs.',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      inputTokenPrice: '0.60',
      cachedInputTokenPrice: '0.30',
      outputTokenPrice: '2.40'
    },
    */
    {
      id: 'o1',
      name: 'o1',
      description: 'Previous full o-series reasoning model.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '15.00',
      cachedInputTokenPrice: '7.50',
      outputTokenPrice: '60.00',
    },
    {
      id: 'o1-pro',
      name: 'o1-pro',
      description: 'Version of o1 with more compute for better responses.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '150.00',
      outputTokenPrice: '600.00',
    },
    {
      id: 'o3-pro',
      name: 'o3-pro',
      description: 'Version of o3 with more compute for better responses.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '20.00',
      outputTokenPrice: '80.00',
    },
    {
      id: 'o3',
      name: 'o3',
      description: 'Most powerful reasoning model.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '2.00',
      cachedInputTokenPrice: '0.50',
      outputTokenPrice: '8.00',
    },
    {
      id: 'o3-deep-research',
      name: 'o3-deep-research',
      description: 'Most powerful deep research model.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '10.00',
      cachedInputTokenPrice: '2.50',
      outputTokenPrice: '40.00',
    },
    {
      id: 'o4-mini',
      name: 'o4-mini',
      description: 'Faster, more affordable reasoning model.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '1.10',
      cachedInputTokenPrice: '0.275',
      outputTokenPrice: '4.40',
    },
    {
      id: 'o4-mini-deep-research',
      name: 'o4-mini-deep-research',
      description: 'Faster, more affordable deep research model.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '2.00',
      cachedInputTokenPrice: '0.50',
      outputTokenPrice: '8.00',
    },
    {
      id: 'o3-mini',
      name: 'o3-mini',
      description: 'A small model alternative to o3.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '1.10',
      cachedInputTokenPrice: '0.55',
      outputTokenPrice: '4.40',
    },
    {
      id: 'o1-mini',
      name: 'o1-mini',
      description: 'A small model alternative to o1.',
      contextWindow: 128000,
      maxOutputTokens: 65536,
      inputTokenPrice: '1.10',
      cachedInputTokenPrice: '0.55',
      outputTokenPrice: '4.40',
    },
    {
      id: 'codex-mini-latest',
      name: 'codex-mini-latest',
      description: 'Fast reasoning model optimized for the Codex CLI.',
      contextWindow: 200000,
      maxOutputTokens: 100000,
      inputTokenPrice: '1.50',
      cachedInputTokenPrice: '0.375',
      outputTokenPrice: '6.00',
    },
    {
      id: 'gpt-4o-mini-search-preview',
      name: 'GPT-4o mini Search Preview',
      description: 'Fast, affordable small model for web search.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '0.15',
      outputTokenPrice: '0.60',
    },
    {
      id: 'gpt-4o-search-preview',
      name: 'GPT-4o Search Preview',
      description: 'GPT model for web search in Chat Completions.',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      inputTokenPrice: '2.50',
      outputTokenPrice: '10.00',
    },
    {
      id: 'computer-use-preview',
      name: 'computer-use-preview',
      description: 'Specialized model for computer use tool.',
      contextWindow: 8192,
      maxOutputTokens: 1024,
      inputTokenPrice: '3.00',
      outputTokenPrice: '12.00',
    },
  ],
  imageModels: [
    {
      id: 'gpt-image-1',
      name: 'GPT Image 1',
      description: 'State-of-the-art image generation model.',
      chargeable: true,
      imageInputTokenPrice: '10.00',
      imageCachedInputTokenPrice: '2.50',
      imageOutputTokenPrice: '40.00',
      textInputTokenPrice: '5.00',
      textCachedInputTokenPrice: '1.25',
      // Computed costs based on image dimensions and quality
      // https://platform.openai.com/docs/guides/image-generation#cost-and-latency
      pricePerImage: [
        [
          'Low',
          [
            ['1024x1024', '0.011'],
            ['1024x1536', '0.016'],
            ['1536x1024', '0.016'],
          ],
        ],
        [
          'Medium',
          [
            ['1024x1024', '0.042'],
            ['1024x1536', '0.063'],
            ['1536x1024', '0.063'],
          ],
        ],
        [
          'High',
          [
            ['1024x1024', '0.167'],
            ['1024x1536', '0.25'],
            ['1536x1024', '0.25'],
          ],
        ],
      ],
    },
    {
      id: 'dall-e-3',
      name: 'DALL·E 3',
      description:
        'DALL·E is an AI system that creates realistic images and art from a natural language description. DALL·E 3 currently supports the ability, given a prompt, to create a new image with a specific size.',
      pricePerImage: [
        [
          'Standard',
          [
            ['1024x1024', '0.04'],
            ['1024x1792', '0.08'],
            ['1792x1024', '0.08'],
          ],
        ],
        [
          'HD',
          [
            ['1024x1024', '0.08'],
            ['1024x1792', '0.12'],
            ['1792x1024', '0.12'],
          ],
        ],
      ],
    },
    {
      id: 'dall-e-2',
      name: 'DALL·E 2',
      description:
        'DALL·E is an AI system that creates realistic images and art from a natural language description. Older than DALL·E 3, DALL·E 2 offers more control in prompting and more requests at once.',
      chargeable: true,
      pricePerImage: [
        [
          'Standard',
          [
            ['256x256', '0.016'],
            ['512x512', '0.018'],
            ['1024x1024', '0.02'],
          ],
        ],
      ],
    },
  ],
  speechModels: [
    {
      id: 'gpt-4o-mini-tts',
      name: 'GPT-4o mini TTS',
      description:
        'GPT-4o mini TTS is a text-to-speech model built on GPT-4o mini, a fast and powerful language model.',
      maxInputTokens: 2000,
      textTokenPrice: '0.60',
      audioTokenPrice: '12.00',
    },
    {
      id: 'tts-1',
      name: 'TTS-1',
      description: 'The tts-1 model is optimized for realtime text-to-speech use cases.',
      textTokenPrice: '15.00',
      audioTokenPrice: '15.00',
    },
    {
      id: 'tts-1-hd',
      name: 'TTS-1 HD',
      description: 'The tts-1-hd model is optimized for high quality text-to-speech use cases.',
      textTokenPrice: '30.00',
      audioTokenPrice: '30.00',
    },
  ],
  transcriptionModels: [
    {
      id: 'gpt-4o-transcribe',
      name: 'GPT-4o Transcribe',
      description:
        'GPT-4o Transcribe is a speech-to-text model that uses GPT-4o to transcribe audio. It offers improvements to word error rate and better language recognition and accuracy compared to original Whisper models.',
      audioTokenPrice: '6.00',
      textInputTokenPrice: '2.50',
      textOutputTokenPrice: '10.00',
    },
    {
      id: 'gpt-4o-mini-transcribe',
      name: 'GPT-4o mini Transcribe',
      description:
        'GPT-4o mini Transcribe is a speech-to-text model that uses GPT-4o mini to transcribe audio. It offers improvements to word error rate and better language recognition and accuracy compared to original Whisper models.',
      audioTokenPrice: '3.00',
      textInputTokenPrice: '1.25',
      textOutputTokenPrice: '5.00',
    },
    {
      id: 'whisper-1',
      name: 'Whisper',
      description:
        'Whisper is a general-purpose speech recognition model, trained on a large dataset of diverse audio.',
    },
  ],
  textEmbeddingModels: [
    {
      id: 'text-embedding-3-small',
      name: 'text-embedding-3-small',
      description: 'Small embedding model.',
      tokenPrice: '0.01',
      dimensions: 1536,
    },
    {
      id: 'text-embedding-3-large',
      name: 'text-embedding-3-large',
      description: 'Most capable embedding model for both english and non-english tasks.',
      tokenPrice: '0.065',
      dimensions: 3072,
    },
    {
      id: 'text-embedding-ada-002',
      name: 'text-embedding-ada-002',
      description: 'Older embedding model.',
      tokenPrice: '0.05',
      dimensions: 1536,
    },
  ],
}

export default openaiProvider
