/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as Acc_Char123accountIdNoPrefixChar125RouteRouteImport } from './routes/acc_{$accountIdNoPrefix}/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Acc_Char123accountIdNoPrefixChar125IndexRouteImport } from './routes/acc_{$accountIdNoPrefix}/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserPricingRouteImport } from './routes/user/pricing'
import { Route as UserApplicationsRouteImport } from './routes/user/applications'
import { Route as UserApiTokensRouteImport } from './routes/user/api-tokens'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminMockRouteImport } from './routes/admin/mock'
import { Route as Acc_Char123accountIdNoPrefixChar125TracingRouteImport } from './routes/acc_{$accountIdNoPrefix}/tracing'
import { Route as Acc_Char123accountIdNoPrefixChar125SettingsRouteImport } from './routes/acc_{$accountIdNoPrefix}/settings'
import { Route as Acc_Char123accountIdNoPrefixChar125ModelsRouteImport } from './routes/acc_{$accountIdNoPrefix}/models'
import { Route as Acc_Char123accountIdNoPrefixChar125MembersRouteImport } from './routes/acc_{$accountIdNoPrefix}/members'
import { Route as Acc_Char123accountIdNoPrefixChar125CreditsRouteImport } from './routes/acc_{$accountIdNoPrefix}/credits'
import { Route as Acc_Char123accountIdNoPrefixChar125AppsRouteImport } from './routes/acc_{$accountIdNoPrefix}/apps'
import { Route as Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport } from './routes/acc_{$accountIdNoPrefix}/api-tokens'
import { Route as Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteImport } from './routes/acc_{$accountIdNoPrefix}_.app_{$appIdNoPrefix}/route'
import { Route as UserWalletIndexRouteImport } from './routes/user/wallet/index'
import { Route as UserSecurityIndexRouteImport } from './routes/user/security/index'
import { Route as AdminAppsIndexRouteImport } from './routes/admin/apps/index'
import { Route as Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRouteImport } from './routes/acc_{$accountIdNoPrefix}_.app_{$appIdNoPrefix}/index'
import { Route as UserApiTokensCreateRouteImport } from './routes/user/api-tokens_.create'
import { Route as AuthOauth2ConsentRouteImport } from './routes/auth/oauth2.consent'
import { Route as AdminAppsTagsRouteImport } from './routes/admin/apps/tags'
import { Route as AdminAppsCategoriesRouteImport } from './routes/admin/apps/categories'
import { Route as Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport } from './routes/acc_{$accountIdNoPrefix}_.accept-invitation.$invitationId'
import { Route as Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport } from './routes/acc_{$accountIdNoPrefix}/members_.invitations'
import { Route as Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport } from './routes/acc_{$accountIdNoPrefix}/credits_.usage'
import { Route as Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport } from './routes/acc_{$accountIdNoPrefix}/api-tokens_.create'
import { Route as Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteImport } from './routes/acc_{$accountIdNoPrefix}_.app_{$appIdNoPrefix}/configure/route'
import { Route as Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRouteImport } from './routes/acc_{$accountIdNoPrefix}_.app_{$appIdNoPrefix}/configure/oauth-application'
import { Route as Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRouteImport } from './routes/acc_{$accountIdNoPrefix}_.app_{$appIdNoPrefix}/configure/api-tokens'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Acc_Char123accountIdNoPrefixChar125RouteRoute =
  Acc_Char123accountIdNoPrefixChar125RouteRouteImport.update({
    id: '/acc_{$accountIdNoPrefix}',
    path: '/acc_{$accountIdNoPrefix}',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125IndexRoute =
  Acc_Char123accountIdNoPrefixChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserPricingRoute = UserPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserApplicationsRoute = UserApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserApiTokensRoute = UserApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => UserRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMockRoute = AdminMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125TracingRoute =
  Acc_Char123accountIdNoPrefixChar125TracingRouteImport.update({
    id: '/tracing',
    path: '/tracing',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125SettingsRoute =
  Acc_Char123accountIdNoPrefixChar125SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ModelsRoute =
  Acc_Char123accountIdNoPrefixChar125ModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125MembersRoute =
  Acc_Char123accountIdNoPrefixChar125MembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125CreditsRoute =
  Acc_Char123accountIdNoPrefixChar125CreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125AppsRoute =
  Acc_Char123accountIdNoPrefixChar125AppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ApiTokensRoute =
  Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteImport.update(
    {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}',
      path: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const UserWalletIndexRoute = UserWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSecurityIndexRoute = UserSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAppsIndexRoute = AdminAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute,
    } as any,
  )
const UserApiTokensCreateRoute = UserApiTokensCreateRouteImport.update({
  id: '/api-tokens_/create',
  path: '/api-tokens/create',
  getParentRoute: () => UserRouteRoute,
} as any)
const AuthOauth2ConsentRoute = AuthOauth2ConsentRouteImport.update({
  id: '/auth/oauth2/consent',
  path: '/auth/oauth2/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppsTagsRoute = AdminAppsTagsRouteImport.update({
  id: '/apps/tags',
  path: '/apps/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppsCategoriesRoute = AdminAppsCategoriesRouteImport.update({
  id: '/apps/categories',
  path: '/apps/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute =
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport.update(
    {
      id: '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId',
      path: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute =
  Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport.update({
    id: '/members_/invitations',
    path: '/members/invitations',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute =
  Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport.update({
    id: '/credits_/usage',
    path: '/credits/usage',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute =
  Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport.update({
    id: '/api-tokens_/create',
    path: '/api-tokens/create',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteImport.update(
    {
      id: '/configure',
      path: '/configure',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRouteImport.update(
    {
      id: '/oauth-application',
      path: '/oauth-application',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRouteImport.update(
    {
      id: '/api-tokens',
      path: '/api-tokens',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/models': typeof ModelsRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/apps': typeof Acc_Char123accountIdNoPrefixChar125AppsRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/landing': typeof LandingIndexRoute
  '/user/': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/admin/apps/categories': typeof AdminAppsCategoriesRoute
  '/admin/apps/tags': typeof AdminAppsTagsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/user/security': typeof UserSecurityIndexRoute
  '/user/wallet': typeof UserWalletIndexRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/oauth-application': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/models': typeof ModelsRoute
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/apps': typeof Acc_Char123accountIdNoPrefixChar125AppsRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin': typeof AdminIndexRoute
  '/landing': typeof LandingIndexRoute
  '/user': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/admin/apps/categories': typeof AdminAppsCategoriesRoute
  '/admin/apps/tags': typeof AdminAppsTagsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/user/security': typeof UserSecurityIndexRoute
  '/user/wallet': typeof UserWalletIndexRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute
  '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/oauth-application': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/models': typeof ModelsRoute
  '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/apps': typeof Acc_Char123accountIdNoPrefixChar125AppsRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/user/': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens_/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits_/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members_/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/admin/apps/categories': typeof AdminAppsCategoriesRoute
  '/admin/apps/tags': typeof AdminAppsTagsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens_/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/user/security/': typeof UserSecurityIndexRoute
  '/user/wallet/': typeof UserWalletIndexRoute
  '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute
  '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/oauth-application': typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/user'
    | '/chat'
    | '/docs'
    | '/models'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/apps'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}/'
    | '/admin/'
    | '/landing'
    | '/user/'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure'
    | '/acc_{$accountIdNoPrefix}/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/credits/usage'
    | '/acc_{$accountIdNoPrefix}/members/invitations'
    | '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
    | '/admin/apps/categories'
    | '/admin/apps/tags'
    | '/auth/oauth2/consent'
    | '/user/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/'
    | '/admin/apps'
    | '/user/security'
    | '/user/wallet'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/api-tokens'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/oauth-application'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/docs'
    | '/models'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/apps'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/landing'
    | '/user'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure'
    | '/acc_{$accountIdNoPrefix}/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/credits/usage'
    | '/acc_{$accountIdNoPrefix}/members/invitations'
    | '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
    | '/admin/apps/categories'
    | '/admin/apps/tags'
    | '/auth/oauth2/consent'
    | '/user/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}'
    | '/admin/apps'
    | '/user/security'
    | '/user/wallet'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/api-tokens'
    | '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/oauth-application'
  id:
    | '__root__'
    | '/'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/user'
    | '/chat'
    | '/docs'
    | '/models'
    | '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/apps'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}/'
    | '/admin/'
    | '/landing/'
    | '/user/'
    | '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure'
    | '/acc_{$accountIdNoPrefix}/api-tokens_/create'
    | '/acc_{$accountIdNoPrefix}/credits_/usage'
    | '/acc_{$accountIdNoPrefix}/members_/invitations'
    | '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId'
    | '/admin/apps/categories'
    | '/admin/apps/tags'
    | '/auth/oauth2/consent'
    | '/user/api-tokens_/create'
    | '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/'
    | '/admin/apps/'
    | '/user/security/'
    | '/user/wallet/'
    | '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/api-tokens'
    | '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/oauth-application'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Acc_Char123accountIdNoPrefixChar125RouteRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  DocsRoute: typeof DocsRoute
  ModelsRoute: typeof ModelsRoute
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  LandingIndexRoute: typeof LandingIndexRoute
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute: typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  AuthOauth2ConsentRoute: typeof AuthOauth2ConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc_{$accountIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}'
      path: '/acc_{$accountIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}/': {
      id: '/acc_{$accountIdNoPrefix}/'
      path: '/'
      fullPath: '/acc_{$accountIdNoPrefix}/'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125IndexRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/pricing': {
      id: '/user/pricing'
      path: '/pricing'
      fullPath: '/user/pricing'
      preLoaderRoute: typeof UserPricingRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/applications': {
      id: '/user/applications'
      path: '/applications'
      fullPath: '/user/applications'
      preLoaderRoute: typeof UserApplicationsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/api-tokens': {
      id: '/user/api-tokens'
      path: '/api-tokens'
      fullPath: '/user/api-tokens'
      preLoaderRoute: typeof UserApiTokensRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mock': {
      id: '/admin/mock'
      path: '/mock'
      fullPath: '/admin/mock'
      preLoaderRoute: typeof AdminMockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}/tracing': {
      id: '/acc_{$accountIdNoPrefix}/tracing'
      path: '/tracing'
      fullPath: '/acc_{$accountIdNoPrefix}/tracing'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125TracingRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/settings': {
      id: '/acc_{$accountIdNoPrefix}/settings'
      path: '/settings'
      fullPath: '/acc_{$accountIdNoPrefix}/settings'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SettingsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/models': {
      id: '/acc_{$accountIdNoPrefix}/models'
      path: '/models'
      fullPath: '/acc_{$accountIdNoPrefix}/models'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ModelsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/members': {
      id: '/acc_{$accountIdNoPrefix}/members'
      path: '/members'
      fullPath: '/acc_{$accountIdNoPrefix}/members'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/credits': {
      id: '/acc_{$accountIdNoPrefix}/credits'
      path: '/credits'
      fullPath: '/acc_{$accountIdNoPrefix}/credits'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/apps': {
      id: '/acc_{$accountIdNoPrefix}/apps'
      path: '/apps'
      fullPath: '/acc_{$accountIdNoPrefix}/apps'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125AppsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/api-tokens': {
      id: '/acc_{$accountIdNoPrefix}/api-tokens'
      path: '/api-tokens'
      fullPath: '/acc_{$accountIdNoPrefix}/api-tokens'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}'
      path: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/wallet/': {
      id: '/user/wallet/'
      path: '/wallet'
      fullPath: '/user/wallet'
      preLoaderRoute: typeof UserWalletIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/security/': {
      id: '/user/security/'
      path: '/security'
      fullPath: '/user/security'
      preLoaderRoute: typeof UserSecurityIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/apps/': {
      id: '/admin/apps/'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/': {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/'
      path: '/'
      fullPath: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute
    }
    '/user/api-tokens_/create': {
      id: '/user/api-tokens_/create'
      path: '/api-tokens/create'
      fullPath: '/user/api-tokens/create'
      preLoaderRoute: typeof UserApiTokensCreateRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/oauth2/consent': {
      id: '/auth/oauth2/consent'
      path: '/auth/oauth2/consent'
      fullPath: '/auth/oauth2/consent'
      preLoaderRoute: typeof AuthOauth2ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps/tags': {
      id: '/admin/apps/tags'
      path: '/apps/tags'
      fullPath: '/admin/apps/tags'
      preLoaderRoute: typeof AdminAppsTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apps/categories': {
      id: '/admin/apps/categories'
      path: '/apps/categories'
      fullPath: '/admin/apps/categories'
      preLoaderRoute: typeof AdminAppsCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId': {
      id: '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId'
      path: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
      fullPath: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc_{$accountIdNoPrefix}/members_/invitations': {
      id: '/acc_{$accountIdNoPrefix}/members_/invitations'
      path: '/members/invitations'
      fullPath: '/acc_{$accountIdNoPrefix}/members/invitations'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/credits_/usage': {
      id: '/acc_{$accountIdNoPrefix}/credits_/usage'
      path: '/credits/usage'
      fullPath: '/acc_{$accountIdNoPrefix}/credits/usage'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/api-tokens_/create': {
      id: '/acc_{$accountIdNoPrefix}/api-tokens_/create'
      path: '/api-tokens/create'
      fullPath: '/acc_{$accountIdNoPrefix}/api-tokens/create'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure': {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure'
      path: '/configure'
      fullPath: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/oauth-application': {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/oauth-application'
      path: '/oauth-application'
      fullPath: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/oauth-application'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/api-tokens': {
      id: '/acc_{$accountIdNoPrefix}_/app_{$appIdNoPrefix}/configure/api-tokens'
      path: '/api-tokens'
      fullPath: '/acc_{$accountIdNoPrefix}/app_{$appIdNoPrefix}/configure/api-tokens'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute
    }
  }
}

interface Acc_Char123accountIdNoPrefixChar125RouteRouteChildren {
  Acc_Char123accountIdNoPrefixChar125ApiTokensRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  Acc_Char123accountIdNoPrefixChar125AppsRoute: typeof Acc_Char123accountIdNoPrefixChar125AppsRoute
  Acc_Char123accountIdNoPrefixChar125CreditsRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  Acc_Char123accountIdNoPrefixChar125MembersRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  Acc_Char123accountIdNoPrefixChar125ModelsRoute: typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  Acc_Char123accountIdNoPrefixChar125SettingsRoute: typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  Acc_Char123accountIdNoPrefixChar125TracingRoute: typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  Acc_Char123accountIdNoPrefixChar125IndexRoute: typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
}

const Acc_Char123accountIdNoPrefixChar125RouteRouteChildren: Acc_Char123accountIdNoPrefixChar125RouteRouteChildren =
  {
    Acc_Char123accountIdNoPrefixChar125ApiTokensRoute:
      Acc_Char123accountIdNoPrefixChar125ApiTokensRoute,
    Acc_Char123accountIdNoPrefixChar125AppsRoute:
      Acc_Char123accountIdNoPrefixChar125AppsRoute,
    Acc_Char123accountIdNoPrefixChar125CreditsRoute:
      Acc_Char123accountIdNoPrefixChar125CreditsRoute,
    Acc_Char123accountIdNoPrefixChar125MembersRoute:
      Acc_Char123accountIdNoPrefixChar125MembersRoute,
    Acc_Char123accountIdNoPrefixChar125ModelsRoute:
      Acc_Char123accountIdNoPrefixChar125ModelsRoute,
    Acc_Char123accountIdNoPrefixChar125SettingsRoute:
      Acc_Char123accountIdNoPrefixChar125SettingsRoute,
    Acc_Char123accountIdNoPrefixChar125TracingRoute:
      Acc_Char123accountIdNoPrefixChar125TracingRoute,
    Acc_Char123accountIdNoPrefixChar125IndexRoute:
      Acc_Char123accountIdNoPrefixChar125IndexRoute,
    Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute:
      Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute,
    Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute:
      Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute,
    Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute:
      Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute,
  }

const Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren =
  Acc_Char123accountIdNoPrefixChar125RouteRoute._addFileChildren(
    Acc_Char123accountIdNoPrefixChar125RouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminMockRoute: typeof AdminMockRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppsCategoriesRoute: typeof AdminAppsCategoriesRoute
  AdminAppsTagsRoute: typeof AdminAppsTagsRoute
  AdminAppsIndexRoute: typeof AdminAppsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMockRoute: AdminMockRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppsCategoriesRoute: AdminAppsCategoriesRoute,
  AdminAppsTagsRoute: AdminAppsTagsRoute,
  AdminAppsIndexRoute: AdminAppsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserApiTokensRoute: typeof UserApiTokensRoute
  UserApplicationsRoute: typeof UserApplicationsRoute
  UserPricingRoute: typeof UserPricingRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
  UserApiTokensCreateRoute: typeof UserApiTokensCreateRoute
  UserSecurityIndexRoute: typeof UserSecurityIndexRoute
  UserWalletIndexRoute: typeof UserWalletIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserApiTokensRoute: UserApiTokensRoute,
  UserApplicationsRoute: UserApplicationsRoute,
  UserPricingRoute: UserPricingRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
  UserApiTokensCreateRoute: UserApiTokensCreateRoute,
  UserSecurityIndexRoute: UserSecurityIndexRoute,
  UserWalletIndexRoute: UserWalletIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteChildren {
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute
}

const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteChildren: Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteChildren =
  {
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute:
      Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureApiTokensRoute,
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute:
      Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureOauthApplicationRoute,
  }

const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute._addFileChildren(
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteChildren,
  )

interface Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteChildren {
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute: typeof Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute
}

const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteChildren: Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteChildren =
  {
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRoute:
      Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125ConfigureRouteRouteWithChildren,
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute:
      Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125IndexRoute,
  }

const Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteWithChildren =
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute._addFileChildren(
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Acc_Char123accountIdNoPrefixChar125RouteRoute:
    Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  DocsRoute: DocsRoute,
  ModelsRoute: ModelsRoute,
  Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRoute:
    Acc_Char123accountIdNoPrefixChar125App_Char123appIdNoPrefixChar125RouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  LandingIndexRoute: LandingIndexRoute,
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute:
    Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute,
  AuthOauth2ConsentRoute: AuthOauth2ConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
