/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as HelioCheckoutRouteImport } from './routes/helio-checkout'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as Acc_Char123accountIdNoPrefixChar125RouteRouteImport } from './routes/acc_{$accountIdNoPrefix}/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Acc_Char123accountIdNoPrefixChar125IndexRouteImport } from './routes/acc_{$accountIdNoPrefix}/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserPricingRouteImport } from './routes/user/pricing'
import { Route as UserApplicationsRouteImport } from './routes/user/applications'
import { Route as UserApiTokensRouteImport } from './routes/user/api-tokens'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminMockRouteImport } from './routes/admin/mock'
import { Route as Acc_Char123accountIdNoPrefixChar125TracingRouteImport } from './routes/acc_{$accountIdNoPrefix}/tracing'
import { Route as Acc_Char123accountIdNoPrefixChar125ToolsRouteImport } from './routes/acc_{$accountIdNoPrefix}/tools'
import { Route as Acc_Char123accountIdNoPrefixChar125SettingsRouteImport } from './routes/acc_{$accountIdNoPrefix}/settings'
import { Route as Acc_Char123accountIdNoPrefixChar125SandboxesRouteImport } from './routes/acc_{$accountIdNoPrefix}/sandboxes'
import { Route as Acc_Char123accountIdNoPrefixChar125OauthAppsRouteImport } from './routes/acc_{$accountIdNoPrefix}/oauth-apps'
import { Route as Acc_Char123accountIdNoPrefixChar125ModelsRouteImport } from './routes/acc_{$accountIdNoPrefix}/models'
import { Route as Acc_Char123accountIdNoPrefixChar125MembersRouteImport } from './routes/acc_{$accountIdNoPrefix}/members'
import { Route as Acc_Char123accountIdNoPrefixChar125McpRouteImport } from './routes/acc_{$accountIdNoPrefix}/mcp'
import { Route as Acc_Char123accountIdNoPrefixChar125IntegrationsRouteImport } from './routes/acc_{$accountIdNoPrefix}/integrations'
import { Route as Acc_Char123accountIdNoPrefixChar125DatabasesRouteImport } from './routes/acc_{$accountIdNoPrefix}/databases'
import { Route as Acc_Char123accountIdNoPrefixChar125CreditsRouteImport } from './routes/acc_{$accountIdNoPrefix}/credits'
import { Route as Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport } from './routes/acc_{$accountIdNoPrefix}/api-tokens'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/route'
import { Route as UserWalletIndexRouteImport } from './routes/user/wallet/index'
import { Route as UserSecurityIndexRouteImport } from './routes/user/security/index'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/index'
import { Route as UserApiTokensCreateRouteImport } from './routes/user/api-tokens_.create'
import { Route as UserApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport } from './routes/user/api-tokens_.at_{$apiTokenIdNoPrefix}'
import { Route as AuthOauth2ConsentRouteImport } from './routes/auth/oauth2.consent'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/settings'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/overview'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/monitoring'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/data-masking'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/data-editor'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/data-api'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/dashboard'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/branches'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/backup-restore'
import { Route as Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRouteImport } from './routes/acc_{$accountIdNoPrefix}_.database_{$namespaceIdNoPrefix}/auth'
import { Route as Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport } from './routes/acc_{$accountIdNoPrefix}_.accept-invitation.$invitationId'
import { Route as Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125RouteImport } from './routes/acc_{$accountIdNoPrefix}/tools_.{$toolkit}'
import { Route as Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRouteImport } from './routes/acc_{$accountIdNoPrefix}/sandboxes_.volumes'
import { Route as Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRouteImport } from './routes/acc_{$accountIdNoPrefix}/sandboxes_.snapshots'
import { Route as Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRouteImport } from './routes/acc_{$accountIdNoPrefix}/sandboxes_.sandboxes'
import { Route as Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125RouteImport } from './routes/acc_{$accountIdNoPrefix}/oauth-apps_.oa_{$oauthAppIdNoPrefix}'
import { Route as Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRouteImport } from './routes/acc_{$accountIdNoPrefix}/oauth-apps_.create'
import { Route as Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport } from './routes/acc_{$accountIdNoPrefix}/members_.invitations'
import { Route as Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport } from './routes/acc_{$accountIdNoPrefix}/credits_.usage'
import { Route as Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport } from './routes/acc_{$accountIdNoPrefix}/api-tokens_.create'
import { Route as Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport } from './routes/acc_{$accountIdNoPrefix}/api-tokens_.at_{$apiTokenIdNoPrefix}'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const HelioCheckoutRoute = HelioCheckoutRouteImport.update({
  id: '/helio-checkout',
  path: '/helio-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Acc_Char123accountIdNoPrefixChar125RouteRoute =
  Acc_Char123accountIdNoPrefixChar125RouteRouteImport.update({
    id: '/acc_{$accountIdNoPrefix}',
    path: '/acc_{$accountIdNoPrefix}',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125IndexRoute =
  Acc_Char123accountIdNoPrefixChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserPricingRoute = UserPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserApplicationsRoute = UserApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserApiTokensRoute = UserApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => UserRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMockRoute = AdminMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125TracingRoute =
  Acc_Char123accountIdNoPrefixChar125TracingRouteImport.update({
    id: '/tracing',
    path: '/tracing',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ToolsRoute =
  Acc_Char123accountIdNoPrefixChar125ToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125SettingsRoute =
  Acc_Char123accountIdNoPrefixChar125SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125SandboxesRoute =
  Acc_Char123accountIdNoPrefixChar125SandboxesRouteImport.update({
    id: '/sandboxes',
    path: '/sandboxes',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125OauthAppsRoute =
  Acc_Char123accountIdNoPrefixChar125OauthAppsRouteImport.update({
    id: '/oauth-apps',
    path: '/oauth-apps',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ModelsRoute =
  Acc_Char123accountIdNoPrefixChar125ModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125MembersRoute =
  Acc_Char123accountIdNoPrefixChar125MembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125McpRoute =
  Acc_Char123accountIdNoPrefixChar125McpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125IntegrationsRoute =
  Acc_Char123accountIdNoPrefixChar125IntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125DatabasesRoute =
  Acc_Char123accountIdNoPrefixChar125DatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125CreditsRoute =
  Acc_Char123accountIdNoPrefixChar125CreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ApiTokensRoute =
  Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteImport.update(
    {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}',
      path: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const UserWalletIndexRoute = UserWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSecurityIndexRoute = UserSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => UserRouteRoute,
} as any)
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const UserApiTokensCreateRoute = UserApiTokensCreateRouteImport.update({
  id: '/api-tokens_/create',
  path: '/api-tokens/create',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route =
  UserApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport.update({
    id: '/api-tokens_/at_{$apiTokenIdNoPrefix}',
    path: '/api-tokens/at_{$apiTokenIdNoPrefix}',
    getParentRoute: () => UserRouteRoute,
  } as any)
const AuthOauth2ConsentRoute = AuthOauth2ConsentRouteImport.update({
  id: '/auth/oauth2/consent',
  path: '/auth/oauth2/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRouteImport.update(
    {
      id: '/overview',
      path: '/overview',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRouteImport.update(
    {
      id: '/monitoring',
      path: '/monitoring',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRouteImport.update(
    {
      id: '/data-masking',
      path: '/data-masking',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRouteImport.update(
    {
      id: '/data-editor',
      path: '/data-editor',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRouteImport.update(
    {
      id: '/data-api',
      path: '/data-api',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRouteImport.update(
    {
      id: '/dashboard',
      path: '/dashboard',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRouteImport.update(
    {
      id: '/branches',
      path: '/branches',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRouteImport.update(
    {
      id: '/backup-restore',
      path: '/backup-restore',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRouteImport.update(
    {
      id: '/auth',
      path: '/auth',
      getParentRoute: () =>
        Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute =
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport.update(
    {
      id: '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId',
      path: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route =
  Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125RouteImport.update(
    {
      id: '/tools_/{$toolkit}',
      path: '/tools/{$toolkit}',
      getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute =
  Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRouteImport.update({
    id: '/sandboxes_/volumes',
    path: '/sandboxes/volumes',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute =
  Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRouteImport.update({
    id: '/sandboxes_/snapshots',
    path: '/sandboxes/snapshots',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute =
  Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRouteImport.update({
    id: '/sandboxes_/sandboxes',
    path: '/sandboxes/sandboxes',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route =
  Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125RouteImport.update(
    {
      id: '/oauth-apps_/oa_{$oauthAppIdNoPrefix}',
      path: '/oauth-apps/oa_{$oauthAppIdNoPrefix}',
      getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
    } as any,
  )
const Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute =
  Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRouteImport.update({
    id: '/oauth-apps_/create',
    path: '/oauth-apps/create',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute =
  Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport.update({
    id: '/members_/invitations',
    path: '/members/invitations',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute =
  Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport.update({
    id: '/credits_/usage',
    path: '/credits/usage',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute =
  Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport.update({
    id: '/api-tokens_/create',
    path: '/api-tokens/create',
    getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
  } as any)
const Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route =
  Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport.update(
    {
      id: '/api-tokens_/at_{$apiTokenIdNoPrefix}',
      path: '/api-tokens/at_{$apiTokenIdNoPrefix}',
      getParentRoute: () => Acc_Char123accountIdNoPrefixChar125RouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/helio-checkout': typeof HelioCheckoutRoute
  '/models': typeof ModelsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/databases': typeof Acc_Char123accountIdNoPrefixChar125DatabasesRoute
  '/acc_{$accountIdNoPrefix}/integrations': typeof Acc_Char123accountIdNoPrefixChar125IntegrationsRoute
  '/acc_{$accountIdNoPrefix}/mcp': typeof Acc_Char123accountIdNoPrefixChar125McpRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tools': typeof Acc_Char123accountIdNoPrefixChar125ToolsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/user/': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}/api-tokens/at_{$apiTokenIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/api-tokens/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps/create': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps/oa_{$oauthAppIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/sandboxes/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute
  '/acc_{$accountIdNoPrefix}/sandboxes/snapshots': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes/volumes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute
  '/acc_{$accountIdNoPrefix}/tools/{$toolkit}': typeof Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route
  '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/auth': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/backup-restore': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/branches': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/dashboard': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-api': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-editor': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-masking': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/monitoring': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/overview': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens/at_{$apiTokenIdNoPrefix}': typeof UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/user/api-tokens/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute
  '/user/security/': typeof UserSecurityIndexRoute
  '/user/wallet/': typeof UserWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/helio-checkout': typeof HelioCheckoutRoute
  '/models': typeof ModelsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/databases': typeof Acc_Char123accountIdNoPrefixChar125DatabasesRoute
  '/acc_{$accountIdNoPrefix}/integrations': typeof Acc_Char123accountIdNoPrefixChar125IntegrationsRoute
  '/acc_{$accountIdNoPrefix}/mcp': typeof Acc_Char123accountIdNoPrefixChar125McpRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tools': typeof Acc_Char123accountIdNoPrefixChar125ToolsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin': typeof AdminIndexRoute
  '/landing': typeof LandingIndexRoute
  '/user': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}/api-tokens/at_{$apiTokenIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/api-tokens/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps/create': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps/oa_{$oauthAppIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/sandboxes/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute
  '/acc_{$accountIdNoPrefix}/sandboxes/snapshots': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes/volumes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute
  '/acc_{$accountIdNoPrefix}/tools/{$toolkit}': typeof Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route
  '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/auth': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/backup-restore': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/branches': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/dashboard': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-api': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-editor': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-masking': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/monitoring': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/overview': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens/at_{$apiTokenIdNoPrefix}': typeof UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/user/api-tokens/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute
  '/user/security': typeof UserSecurityIndexRoute
  '/user/wallet': typeof UserWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acc_{$accountIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/helio-checkout': typeof HelioCheckoutRoute
  '/models': typeof ModelsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteWithChildren
  '/acc_{$accountIdNoPrefix}/api-tokens': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  '/acc_{$accountIdNoPrefix}/credits': typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  '/acc_{$accountIdNoPrefix}/databases': typeof Acc_Char123accountIdNoPrefixChar125DatabasesRoute
  '/acc_{$accountIdNoPrefix}/integrations': typeof Acc_Char123accountIdNoPrefixChar125IntegrationsRoute
  '/acc_{$accountIdNoPrefix}/mcp': typeof Acc_Char123accountIdNoPrefixChar125McpRoute
  '/acc_{$accountIdNoPrefix}/members': typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  '/acc_{$accountIdNoPrefix}/models': typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesRoute
  '/acc_{$accountIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  '/acc_{$accountIdNoPrefix}/tools': typeof Acc_Char123accountIdNoPrefixChar125ToolsRoute
  '/acc_{$accountIdNoPrefix}/tracing': typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  '/admin/mock': typeof AdminMockRoute
  '/admin/models': typeof AdminModelsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/user/api-tokens': typeof UserApiTokensRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/pricing': typeof UserPricingRoute
  '/user/profile': typeof UserProfileRoute
  '/acc_{$accountIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/user/': typeof UserIndexRoute
  '/acc_{$accountIdNoPrefix}/api-tokens_/at_{$apiTokenIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/api-tokens_/create': typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}/credits_/usage': typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  '/acc_{$accountIdNoPrefix}/members_/invitations': typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps_/create': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute
  '/acc_{$accountIdNoPrefix}/oauth-apps_/oa_{$oauthAppIdNoPrefix}': typeof Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route
  '/acc_{$accountIdNoPrefix}/sandboxes_/sandboxes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute
  '/acc_{$accountIdNoPrefix}/sandboxes_/snapshots': typeof Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute
  '/acc_{$accountIdNoPrefix}/sandboxes_/volumes': typeof Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute
  '/acc_{$accountIdNoPrefix}/tools_/{$toolkit}': typeof Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route
  '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId': typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/auth': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/backup-restore': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/branches': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/dashboard': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-api': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-editor': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-masking': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/monitoring': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/overview': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/settings': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute
  '/auth/oauth2/consent': typeof AuthOauth2ConsentRoute
  '/user/api-tokens_/at_{$apiTokenIdNoPrefix}': typeof UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  '/user/api-tokens_/create': typeof UserApiTokensCreateRoute
  '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/': typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute
  '/user/security/': typeof UserSecurityIndexRoute
  '/user/wallet/': typeof UserWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/user'
    | '/chat'
    | '/docs'
    | '/helio-checkout'
    | '/models'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/tools'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/databases'
    | '/acc_{$accountIdNoPrefix}/integrations'
    | '/acc_{$accountIdNoPrefix}/mcp'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/oauth-apps'
    | '/acc_{$accountIdNoPrefix}/sandboxes'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tools'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}/'
    | '/admin/'
    | '/landing/'
    | '/user/'
    | '/acc_{$accountIdNoPrefix}/api-tokens/at_{$apiTokenIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/credits/usage'
    | '/acc_{$accountIdNoPrefix}/members/invitations'
    | '/acc_{$accountIdNoPrefix}/oauth-apps/create'
    | '/acc_{$accountIdNoPrefix}/oauth-apps/oa_{$oauthAppIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/sandboxes/sandboxes'
    | '/acc_{$accountIdNoPrefix}/sandboxes/snapshots'
    | '/acc_{$accountIdNoPrefix}/sandboxes/volumes'
    | '/acc_{$accountIdNoPrefix}/tools/{$toolkit}'
    | '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/auth'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/backup-restore'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/branches'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/dashboard'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-api'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-editor'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-masking'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/monitoring'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/overview'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/settings'
    | '/auth/oauth2/consent'
    | '/user/api-tokens/at_{$apiTokenIdNoPrefix}'
    | '/user/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/'
    | '/user/security/'
    | '/user/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/docs'
    | '/helio-checkout'
    | '/models'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/tools'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/databases'
    | '/acc_{$accountIdNoPrefix}/integrations'
    | '/acc_{$accountIdNoPrefix}/mcp'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/oauth-apps'
    | '/acc_{$accountIdNoPrefix}/sandboxes'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tools'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/landing'
    | '/user'
    | '/acc_{$accountIdNoPrefix}/api-tokens/at_{$apiTokenIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/credits/usage'
    | '/acc_{$accountIdNoPrefix}/members/invitations'
    | '/acc_{$accountIdNoPrefix}/oauth-apps/create'
    | '/acc_{$accountIdNoPrefix}/oauth-apps/oa_{$oauthAppIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/sandboxes/sandboxes'
    | '/acc_{$accountIdNoPrefix}/sandboxes/snapshots'
    | '/acc_{$accountIdNoPrefix}/sandboxes/volumes'
    | '/acc_{$accountIdNoPrefix}/tools/{$toolkit}'
    | '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/auth'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/backup-restore'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/branches'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/dashboard'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-api'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-editor'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-masking'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/monitoring'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/overview'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/settings'
    | '/auth/oauth2/consent'
    | '/user/api-tokens/at_{$apiTokenIdNoPrefix}'
    | '/user/api-tokens/create'
    | '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}'
    | '/user/security'
    | '/user/wallet'
  id:
    | '__root__'
    | '/'
    | '/acc_{$accountIdNoPrefix}'
    | '/admin'
    | '/user'
    | '/chat'
    | '/docs'
    | '/helio-checkout'
    | '/models'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/tools'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens'
    | '/acc_{$accountIdNoPrefix}/credits'
    | '/acc_{$accountIdNoPrefix}/databases'
    | '/acc_{$accountIdNoPrefix}/integrations'
    | '/acc_{$accountIdNoPrefix}/mcp'
    | '/acc_{$accountIdNoPrefix}/members'
    | '/acc_{$accountIdNoPrefix}/models'
    | '/acc_{$accountIdNoPrefix}/oauth-apps'
    | '/acc_{$accountIdNoPrefix}/sandboxes'
    | '/acc_{$accountIdNoPrefix}/settings'
    | '/acc_{$accountIdNoPrefix}/tools'
    | '/acc_{$accountIdNoPrefix}/tracing'
    | '/admin/mock'
    | '/admin/models'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/api-tokens'
    | '/user/applications'
    | '/user/pricing'
    | '/user/profile'
    | '/acc_{$accountIdNoPrefix}/'
    | '/admin/'
    | '/landing/'
    | '/user/'
    | '/acc_{$accountIdNoPrefix}/api-tokens_/at_{$apiTokenIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/api-tokens_/create'
    | '/acc_{$accountIdNoPrefix}/credits_/usage'
    | '/acc_{$accountIdNoPrefix}/members_/invitations'
    | '/acc_{$accountIdNoPrefix}/oauth-apps_/create'
    | '/acc_{$accountIdNoPrefix}/oauth-apps_/oa_{$oauthAppIdNoPrefix}'
    | '/acc_{$accountIdNoPrefix}/sandboxes_/sandboxes'
    | '/acc_{$accountIdNoPrefix}/sandboxes_/snapshots'
    | '/acc_{$accountIdNoPrefix}/sandboxes_/volumes'
    | '/acc_{$accountIdNoPrefix}/tools_/{$toolkit}'
    | '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/auth'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/backup-restore'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/branches'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/dashboard'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-api'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-editor'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-masking'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/monitoring'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/overview'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/settings'
    | '/auth/oauth2/consent'
    | '/user/api-tokens_/at_{$apiTokenIdNoPrefix}'
    | '/user/api-tokens_/create'
    | '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/'
    | '/user/security/'
    | '/user/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Acc_Char123accountIdNoPrefixChar125RouteRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  DocsRoute: typeof DocsRoute
  HelioCheckoutRoute: typeof HelioCheckoutRoute
  ModelsRoute: typeof ModelsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ToolsRoute: typeof ToolsRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  LandingIndexRoute: typeof LandingIndexRoute
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute: typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute
  AuthOauth2ConsentRoute: typeof AuthOauth2ConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helio-checkout': {
      id: '/helio-checkout'
      path: '/helio-checkout'
      fullPath: '/helio-checkout'
      preLoaderRoute: typeof HelioCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc_{$accountIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}'
      path: '/acc_{$accountIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}/': {
      id: '/acc_{$accountIdNoPrefix}/'
      path: '/'
      fullPath: '/acc_{$accountIdNoPrefix}/'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125IndexRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/pricing': {
      id: '/user/pricing'
      path: '/pricing'
      fullPath: '/user/pricing'
      preLoaderRoute: typeof UserPricingRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/applications': {
      id: '/user/applications'
      path: '/applications'
      fullPath: '/user/applications'
      preLoaderRoute: typeof UserApplicationsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/api-tokens': {
      id: '/user/api-tokens'
      path: '/api-tokens'
      fullPath: '/user/api-tokens'
      preLoaderRoute: typeof UserApiTokensRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mock': {
      id: '/admin/mock'
      path: '/mock'
      fullPath: '/admin/mock'
      preLoaderRoute: typeof AdminMockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/acc_{$accountIdNoPrefix}/tracing': {
      id: '/acc_{$accountIdNoPrefix}/tracing'
      path: '/tracing'
      fullPath: '/acc_{$accountIdNoPrefix}/tracing'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125TracingRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/tools': {
      id: '/acc_{$accountIdNoPrefix}/tools'
      path: '/tools'
      fullPath: '/acc_{$accountIdNoPrefix}/tools'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ToolsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/settings': {
      id: '/acc_{$accountIdNoPrefix}/settings'
      path: '/settings'
      fullPath: '/acc_{$accountIdNoPrefix}/settings'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SettingsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/sandboxes': {
      id: '/acc_{$accountIdNoPrefix}/sandboxes'
      path: '/sandboxes'
      fullPath: '/acc_{$accountIdNoPrefix}/sandboxes'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/oauth-apps': {
      id: '/acc_{$accountIdNoPrefix}/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/acc_{$accountIdNoPrefix}/oauth-apps'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/models': {
      id: '/acc_{$accountIdNoPrefix}/models'
      path: '/models'
      fullPath: '/acc_{$accountIdNoPrefix}/models'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ModelsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/members': {
      id: '/acc_{$accountIdNoPrefix}/members'
      path: '/members'
      fullPath: '/acc_{$accountIdNoPrefix}/members'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/mcp': {
      id: '/acc_{$accountIdNoPrefix}/mcp'
      path: '/mcp'
      fullPath: '/acc_{$accountIdNoPrefix}/mcp'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125McpRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/integrations': {
      id: '/acc_{$accountIdNoPrefix}/integrations'
      path: '/integrations'
      fullPath: '/acc_{$accountIdNoPrefix}/integrations'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125IntegrationsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/databases': {
      id: '/acc_{$accountIdNoPrefix}/databases'
      path: '/databases'
      fullPath: '/acc_{$accountIdNoPrefix}/databases'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125DatabasesRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/credits': {
      id: '/acc_{$accountIdNoPrefix}/credits'
      path: '/credits'
      fullPath: '/acc_{$accountIdNoPrefix}/credits'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/api-tokens': {
      id: '/acc_{$accountIdNoPrefix}/api-tokens'
      path: '/api-tokens'
      fullPath: '/acc_{$accountIdNoPrefix}/api-tokens'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}'
      path: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/wallet/': {
      id: '/user/wallet/'
      path: '/wallet'
      fullPath: '/user/wallet/'
      preLoaderRoute: typeof UserWalletIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/security/': {
      id: '/user/security/'
      path: '/security'
      fullPath: '/user/security/'
      preLoaderRoute: typeof UserSecurityIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/'
      path: '/'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/user/api-tokens_/create': {
      id: '/user/api-tokens_/create'
      path: '/api-tokens/create'
      fullPath: '/user/api-tokens/create'
      preLoaderRoute: typeof UserApiTokensCreateRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/api-tokens_/at_{$apiTokenIdNoPrefix}': {
      id: '/user/api-tokens_/at_{$apiTokenIdNoPrefix}'
      path: '/api-tokens/at_{$apiTokenIdNoPrefix}'
      fullPath: '/user/api-tokens/at_{$apiTokenIdNoPrefix}'
      preLoaderRoute: typeof UserApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/oauth2/consent': {
      id: '/auth/oauth2/consent'
      path: '/auth/oauth2/consent'
      fullPath: '/auth/oauth2/consent'
      preLoaderRoute: typeof AuthOauth2ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/settings': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/settings'
      path: '/settings'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/settings'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/overview': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/overview'
      path: '/overview'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/overview'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/monitoring': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/monitoring'
      path: '/monitoring'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/monitoring'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-masking': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-masking'
      path: '/data-masking'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-masking'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-editor': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-editor'
      path: '/data-editor'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-editor'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-api': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/data-api'
      path: '/data-api'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/data-api'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/dashboard': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/dashboard'
      path: '/dashboard'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/dashboard'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/branches': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/branches'
      path: '/branches'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/branches'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/backup-restore': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/backup-restore'
      path: '/backup-restore'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/backup-restore'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/auth': {
      id: '/acc_{$accountIdNoPrefix}_/database_{$namespaceIdNoPrefix}/auth'
      path: '/auth'
      fullPath: '/acc_{$accountIdNoPrefix}/database_{$namespaceIdNoPrefix}/auth'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId': {
      id: '/acc_{$accountIdNoPrefix}_/accept-invitation/$invitationId'
      path: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
      fullPath: '/acc_{$accountIdNoPrefix}/accept-invitation/$invitationId'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc_{$accountIdNoPrefix}/tools_/{$toolkit}': {
      id: '/acc_{$accountIdNoPrefix}/tools_/{$toolkit}'
      path: '/tools/{$toolkit}'
      fullPath: '/acc_{$accountIdNoPrefix}/tools/{$toolkit}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125RouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/sandboxes_/volumes': {
      id: '/acc_{$accountIdNoPrefix}/sandboxes_/volumes'
      path: '/sandboxes/volumes'
      fullPath: '/acc_{$accountIdNoPrefix}/sandboxes/volumes'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/sandboxes_/snapshots': {
      id: '/acc_{$accountIdNoPrefix}/sandboxes_/snapshots'
      path: '/sandboxes/snapshots'
      fullPath: '/acc_{$accountIdNoPrefix}/sandboxes/snapshots'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/sandboxes_/sandboxes': {
      id: '/acc_{$accountIdNoPrefix}/sandboxes_/sandboxes'
      path: '/sandboxes/sandboxes'
      fullPath: '/acc_{$accountIdNoPrefix}/sandboxes/sandboxes'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/oauth-apps_/oa_{$oauthAppIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}/oauth-apps_/oa_{$oauthAppIdNoPrefix}'
      path: '/oauth-apps/oa_{$oauthAppIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}/oauth-apps/oa_{$oauthAppIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125RouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/oauth-apps_/create': {
      id: '/acc_{$accountIdNoPrefix}/oauth-apps_/create'
      path: '/oauth-apps/create'
      fullPath: '/acc_{$accountIdNoPrefix}/oauth-apps/create'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/members_/invitations': {
      id: '/acc_{$accountIdNoPrefix}/members_/invitations'
      path: '/members/invitations'
      fullPath: '/acc_{$accountIdNoPrefix}/members/invitations'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/credits_/usage': {
      id: '/acc_{$accountIdNoPrefix}/credits_/usage'
      path: '/credits/usage'
      fullPath: '/acc_{$accountIdNoPrefix}/credits/usage'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/api-tokens_/create': {
      id: '/acc_{$accountIdNoPrefix}/api-tokens_/create'
      path: '/api-tokens/create'
      fullPath: '/acc_{$accountIdNoPrefix}/api-tokens/create'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
    '/acc_{$accountIdNoPrefix}/api-tokens_/at_{$apiTokenIdNoPrefix}': {
      id: '/acc_{$accountIdNoPrefix}/api-tokens_/at_{$apiTokenIdNoPrefix}'
      path: '/api-tokens/at_{$apiTokenIdNoPrefix}'
      fullPath: '/acc_{$accountIdNoPrefix}/api-tokens/at_{$apiTokenIdNoPrefix}'
      preLoaderRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125RouteImport
      parentRoute: typeof Acc_Char123accountIdNoPrefixChar125RouteRoute
    }
  }
}

interface Acc_Char123accountIdNoPrefixChar125RouteRouteChildren {
  Acc_Char123accountIdNoPrefixChar125ApiTokensRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensRoute
  Acc_Char123accountIdNoPrefixChar125CreditsRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsRoute
  Acc_Char123accountIdNoPrefixChar125DatabasesRoute: typeof Acc_Char123accountIdNoPrefixChar125DatabasesRoute
  Acc_Char123accountIdNoPrefixChar125IntegrationsRoute: typeof Acc_Char123accountIdNoPrefixChar125IntegrationsRoute
  Acc_Char123accountIdNoPrefixChar125McpRoute: typeof Acc_Char123accountIdNoPrefixChar125McpRoute
  Acc_Char123accountIdNoPrefixChar125MembersRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersRoute
  Acc_Char123accountIdNoPrefixChar125ModelsRoute: typeof Acc_Char123accountIdNoPrefixChar125ModelsRoute
  Acc_Char123accountIdNoPrefixChar125OauthAppsRoute: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsRoute
  Acc_Char123accountIdNoPrefixChar125SandboxesRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesRoute
  Acc_Char123accountIdNoPrefixChar125SettingsRoute: typeof Acc_Char123accountIdNoPrefixChar125SettingsRoute
  Acc_Char123accountIdNoPrefixChar125ToolsRoute: typeof Acc_Char123accountIdNoPrefixChar125ToolsRoute
  Acc_Char123accountIdNoPrefixChar125TracingRoute: typeof Acc_Char123accountIdNoPrefixChar125TracingRoute
  Acc_Char123accountIdNoPrefixChar125IndexRoute: typeof Acc_Char123accountIdNoPrefixChar125IndexRoute
  Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute: typeof Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute
  Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute: typeof Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute
  Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute: typeof Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute
  Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute
  Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route: typeof Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route
  Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute
  Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute
  Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute: typeof Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute
  Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route: typeof Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route
}

const Acc_Char123accountIdNoPrefixChar125RouteRouteChildren: Acc_Char123accountIdNoPrefixChar125RouteRouteChildren =
  {
    Acc_Char123accountIdNoPrefixChar125ApiTokensRoute:
      Acc_Char123accountIdNoPrefixChar125ApiTokensRoute,
    Acc_Char123accountIdNoPrefixChar125CreditsRoute:
      Acc_Char123accountIdNoPrefixChar125CreditsRoute,
    Acc_Char123accountIdNoPrefixChar125DatabasesRoute:
      Acc_Char123accountIdNoPrefixChar125DatabasesRoute,
    Acc_Char123accountIdNoPrefixChar125IntegrationsRoute:
      Acc_Char123accountIdNoPrefixChar125IntegrationsRoute,
    Acc_Char123accountIdNoPrefixChar125McpRoute:
      Acc_Char123accountIdNoPrefixChar125McpRoute,
    Acc_Char123accountIdNoPrefixChar125MembersRoute:
      Acc_Char123accountIdNoPrefixChar125MembersRoute,
    Acc_Char123accountIdNoPrefixChar125ModelsRoute:
      Acc_Char123accountIdNoPrefixChar125ModelsRoute,
    Acc_Char123accountIdNoPrefixChar125OauthAppsRoute:
      Acc_Char123accountIdNoPrefixChar125OauthAppsRoute,
    Acc_Char123accountIdNoPrefixChar125SandboxesRoute:
      Acc_Char123accountIdNoPrefixChar125SandboxesRoute,
    Acc_Char123accountIdNoPrefixChar125SettingsRoute:
      Acc_Char123accountIdNoPrefixChar125SettingsRoute,
    Acc_Char123accountIdNoPrefixChar125ToolsRoute:
      Acc_Char123accountIdNoPrefixChar125ToolsRoute,
    Acc_Char123accountIdNoPrefixChar125TracingRoute:
      Acc_Char123accountIdNoPrefixChar125TracingRoute,
    Acc_Char123accountIdNoPrefixChar125IndexRoute:
      Acc_Char123accountIdNoPrefixChar125IndexRoute,
    Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route:
      Acc_Char123accountIdNoPrefixChar125ApiTokensAt_Char123apiTokenIdNoPrefixChar125Route,
    Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute:
      Acc_Char123accountIdNoPrefixChar125ApiTokensCreateRoute,
    Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute:
      Acc_Char123accountIdNoPrefixChar125CreditsUsageRoute,
    Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute:
      Acc_Char123accountIdNoPrefixChar125MembersInvitationsRoute,
    Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute:
      Acc_Char123accountIdNoPrefixChar125OauthAppsCreateRoute,
    Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route:
      Acc_Char123accountIdNoPrefixChar125OauthAppsOa_Char123oauthAppIdNoPrefixChar125Route,
    Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute:
      Acc_Char123accountIdNoPrefixChar125SandboxesSandboxesRoute,
    Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute:
      Acc_Char123accountIdNoPrefixChar125SandboxesSnapshotsRoute,
    Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute:
      Acc_Char123accountIdNoPrefixChar125SandboxesVolumesRoute,
    Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route:
      Acc_Char123accountIdNoPrefixChar125ToolsChar123toolkitChar125Route,
  }

const Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren =
  Acc_Char123accountIdNoPrefixChar125RouteRoute._addFileChildren(
    Acc_Char123accountIdNoPrefixChar125RouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminMockRoute: typeof AdminMockRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMockRoute: AdminMockRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserApiTokensRoute: typeof UserApiTokensRoute
  UserApplicationsRoute: typeof UserApplicationsRoute
  UserPricingRoute: typeof UserPricingRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
  UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route: typeof UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route
  UserApiTokensCreateRoute: typeof UserApiTokensCreateRoute
  UserSecurityIndexRoute: typeof UserSecurityIndexRoute
  UserWalletIndexRoute: typeof UserWalletIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserApiTokensRoute: UserApiTokensRoute,
  UserApplicationsRoute: UserApplicationsRoute,
  UserPricingRoute: UserPricingRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
  UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route:
    UserApiTokensAt_Char123apiTokenIdNoPrefixChar125Route,
  UserApiTokensCreateRoute: UserApiTokensCreateRoute,
  UserSecurityIndexRoute: UserSecurityIndexRoute,
  UserWalletIndexRoute: UserWalletIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteChildren {
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute: typeof Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute
}

const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteChildren: Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteChildren =
  {
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125AuthRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BackupRestoreRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125BranchesRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DashboardRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataApiRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataEditorRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125DataMaskingRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125MonitoringRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125OverviewRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125SettingsRoute,
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute:
      Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125IndexRoute,
  }

const Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteWithChildren =
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute._addFileChildren(
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Acc_Char123accountIdNoPrefixChar125RouteRoute:
    Acc_Char123accountIdNoPrefixChar125RouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  DocsRoute: DocsRoute,
  HelioCheckoutRoute: HelioCheckoutRoute,
  ModelsRoute: ModelsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ToolsRoute: ToolsRoute,
  Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRoute:
    Acc_Char123accountIdNoPrefixChar125Database_Char123namespaceIdNoPrefixChar125RouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  LandingIndexRoute: LandingIndexRoute,
  Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute:
    Acc_Char123accountIdNoPrefixChar125AcceptInvitationInvitationIdRoute,
  AuthOauth2ConsentRoute: AuthOauth2ConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
